Improved memory configuration.

diff --git a/make-vm b/make-vm
--- a/make-vm
+++ b/make-vm
@@ -37,6 +37,7 @@ VM_CHIPSET=ich9
 VM_FIRMWARE=efi
 VM_CORES=4
 VM_MEMORY=4096
+VM_BALLOON=0
 
 USE_SEPARATE_DISKS=1
 VM_DISK_ROOT=32768
@@ -151,6 +152,13 @@ while [ $# -gt 0 ] ; do
          if [ ${VM_MEMORY} -lt 64 ] ; then
             VM_MEMORY=64
          fi
+      fi
+      shift
+   elif [ "$1" == "--balloon" -o "$1" == "-b" ] ; then
+      VM_BALLOON="$2"
+      if [[ ! "${VM_BALLOON}" =~ ^[0-9]*$|^NA$ ]] ; then
+         echo >&2 "ERROR: Bad size for memory balloon: ${VM_BALLOON} MiB"
+         exit 1
       fi
       shift
    elif [ "$1" == "--root" -o "$1" == "-r" ] ; then
@@ -282,6 +290,7 @@ while [ $# -gt 0 ] ; do
       echo >&2 "   [--firmware|-F efi|bios]"
       echo >&2 "   [--cores|-c cores]"
       echo >&2 "   [--memory|-m MiB]"
+      echo >&2 "   [--balloon|-b MiB]"
       echo >&2 "   [--root|-r MiB]"
       echo >&2 "   [--home|-h MiB]"
       echo >&2 "   [--swap|-s MiB]"
@@ -448,6 +457,12 @@ fi
 USER_HASHED_PASSWORD=`echo "${USER_PASSWORD}" | mkpasswd -s -m sha-512`
 HOSTNAME=`echo "${FQDN}" | sed -e 's/\([a-zA-Z0-9]*\)\.\([a-zA-Z0-9\.]*\)/\1/g'`
 DOMAINNAME=`echo "${FQDN}" | sed -e 's/\([a-zA-Z0-9]*\)\.\([a-zA-Z0-9\.]*\)/\2/g'`
+
+let VM_BALLOON_MIN=${VM_MEMORY}-${VM_BALLOON}
+if [ ${VM_BALLOON_MIN} -lt 0 ] ; then
+   echo >&2 "ERROR: Bad memory settings: VM_MEMORY=${VM_MEMORY}, VM_BALLOON=${VM_BALLOON} => ${VM_BALLOON_MIN}"
+   exit 1
+fi
 
 
 # ###### Check Packer version ###############################################
@@ -692,6 +707,7 @@ echo " - VM_CHIPSET=${VM_CHIPSET}"
 echo " - VM_FIRMWARE=${VM_FIRMWARE}"
 echo " - VM_CORES=${VM_CORES}"
 echo " - VM_MEMORY=${VM_MEMORY} (MiB)"
+echo " - VM_BALLOON=${VM_BALLOON} (MiB)"
 echo " - VM_DISK_PREFIX=${VM_DISK_PREFIX}"
 echo " - VM_DISK_ROOT=${VM_DISK_ROOT} (MiB)"
 if [ ${USE_SEPARATE_DISKS} -ne 0 ] ; then
@@ -742,6 +758,8 @@ env CHECKPOINT_DISABLE=1 PACKER_LOG=${PACKER_LOG} PACKER_CACHE_DIR="${CACHE_DIRE
    -var "vm_firmware=${VM_FIRMWARE}"       \
    -var "vm_cores=${VM_CORES}"             \
    -var "vm_memory=${VM_MEMORY}"           \
+   -var "vm_balloon=${VM_BALLOON}"          \
+   -var "vm_balloon_min=${VM_BALLOON_MIN}" \
    -var "vm_disk_prefix=${VM_DISK_PREFIX}" \
    -var "vm_disk_root=${VM_DISK_ROOT}"     \
    -var "vm_disk_home=${VM_DISK_HOME}"     \
