Added initial Docker support.

diff --git a/make-vm b/make-vm
--- a/make-vm
+++ b/make-vm
@@ -103,23 +103,26 @@ while [ $# -gt 0 ] ; do
       shift
    elif [ "$1" == "--chipset" -o "$1" == "-I" ] ; then
       VM_CHIPSET="$2"
-      if [[ ! "${VM_CHIPSET}" =~ ^ich9|piix3$ ]] ; then
+      if [[ ! "${VM_CHIPSET}" =~ ^ich9$|^piix3$|^NA$ ]] ; then
          echo >&2 "ERROR: Bad chipset setting: ${VM_CHIPSET}"
          exit 1
       fi
       shift
    elif [ "$1" == "--firmware" -o "$1" == "-F" ] ; then
       VM_FIRMWARE="$2"
-      if [[ ! "${VM_FIRMWARE}" =~ ^efi|bios$ ]] ; then
+      if [[ ! "${VM_FIRMWARE}" =~ ^efi$|^bios$|^NA$ ]] ; then
          echo >&2 "ERROR: Bad firmware setting: ${VM_FIRMWARE}"
          exit 1
       fi
       shift
    elif [ "$1" == "--cores" -o "$1" == "-c" ] ; then
       VM_CORES="$2"
-      if [[ ! "${VM_CORES}" =~ ^[0-9]*$ ]] ; then
+      if [[ ! "${VM_CORES}" =~ ^[0-9]*|NA$ ]] ; then
          echo >&2 "ERROR: Bad value for cores: ${VM_CORES}"
          exit 1
+      fi
+      if [ "${VM_CORES}" == "NA" ] ; then
+         VM_CORES=1
       fi
       if [ ${VM_CORES} -lt 1 ] ; then
          VM_CORES=1
@@ -127,33 +130,50 @@ while [ $# -gt 0 ] ; do
       shift
    elif [ "$1" == "--memory" -o "$1" == "-m" ] ; then
       VM_MEMORY="$2"
-      if [[ ! "${VM_MEMORY}" =~ ^[0-9]*$ ]] ; then
+      if [[ ! "${VM_MEMORY}" =~ ^[0-9]*$|^NA$ ]] ; then
          echo >&2 "ERROR: Bad size for memory: ${VM_MEMORY} MiB"
          exit 1
       fi
-      if [ ${VM_MEMORY} -lt 64 ] ; then
-         VM_MEMORY=64
+      if [ ${VM_MEMORY} != "NA" ] ; then
+         if [ ${VM_MEMORY} -lt 64 ] ; then
+            VM_MEMORY=64
+         fi
       fi
       shift
    elif [ "$1" == "--root" -o "$1" == "-r" ] ; then
       VM_DISK_ROOT="$2"
-      if [[ ! "${VM_DISK_ROOT}" =~ ^[0-9]*$ ]] ; then
+      if [[ ! "${VM_DISK_ROOT}" =~ ^[0-9]*$|^NA$ ]] ; then
          echo >&2 "ERROR: Bad size for root: ${VM_DISK_ROOT} MiB"
          exit 1
+      fi
+      if [ ${VM_DISK_ROOT} != "NA" ] ; then
+         if [ ${VM_DISK_ROOT} -lt 64 ] ; then
+            VM_DISK_ROOT=64
+         fi
       fi
       shift
    elif [ "$1" == "--home" -o "$1" == "-r" ] ; then
       VM_DISK_HOME="$2"
-      if [[ ! "${VM_DISK_HOME}" =~ ^[0-9]*$ ]] ; then
+      if [[ ! "${VM_DISK_HOME}" =~ ^[0-9]*$|^NA$ ]] ; then
          echo >&2 "ERROR: Bad size for home: ${VM_DISK_HOME} MiB"
          exit 1
+      fi
+      if [ ${VM_DISK_HOME} != "NA" ] ; then
+         if [ ${VM_DISK_HOME} -lt 64 ] ; then
+            VM_DISK_HOME=64
+         fi
       fi
       shift
    elif [ "$1" == "--swap" -o "$1" == "-r" ] ; then
       VM_DISK_SWAP="$2"
-      if [[ ! "${VM_DISK_SWAP}" =~ ^[0-9]*$ ]] ; then
+      if [[ ! "${VM_DISK_SWAP}" =~ ^[0-9]*$|^NA$ ]] ; then
          echo >&2 "ERROR: Bad size for swap: ${VM_DISK_SWAP} MiB"
          exit 1
+      fi
+      if [ ${VM_DISK_SWAP} != "NA" ] ; then
+         if [ ${VM_DISK_SWAP} -lt 0 ] ; then
+            VM_DISK_SWAP=0
+         fi
       fi
       shift
    elif [ "$1" == "--one-disk-only" -o "$1" == "-1" ] ; then
@@ -173,9 +193,11 @@ while [ $# -gt 0 ] ; do
       elif [ "${VIDEO}" == "UHD" ] ; then
          VIDEO="3840x2160"  # 4K, 16:9
       fi
-      if [[ ! "${VIDEO}" =~ ^[0-9]*x[0-9]*$ ]] ; then
-         echo >&2 "ERROR: Bad video setting: ${VIDEO}"
-         exit 1
+      if [ ${VIDEO} != "NA" ] ; then
+         if [[ ! "${VIDEO}" =~ ^[0-9]*x[0-9]*$ ]] ; then
+            echo >&2 "ERROR: Bad video setting: ${VIDEO}"
+            exit 1
+         fi
       fi
       shift
    elif [ "$1" == "--keyboard-model" -o "$1" == "-m" ] ; then
@@ -289,6 +311,9 @@ elif [ "${HYPERVISOR}" == "vSphere" ] ; then
       exit 1
    fi
    source "${VSPHERE_CONFIG_FILE}"
+elif [ "${HYPERVISOR}" == "Docker" ] ; then
+   BUILDER_VMSETUP="docker"
+   NAME="Docker"
 else
    echo >&2 "ERROR: Invalid hypervisor ${HYPERVISOR}!"
    exit 1
@@ -457,11 +482,26 @@ for httpFile in ${httpFiles} ; do
 done
 
 # Configure HTTP directory:
+if [ ! -e vmsetup/${BUILDER_VMSETUP}.json ] ; then
+   echo >&2 "ERROR: vmsetup/${BUILDER_VMSETUP}.json does not exist!"
+   exit 1
+fi
+if [ "${HYPERVISOR}" == "Docker" ] ; then
+   BUILDER_INSTALLTYPE="docker"
+else
+   BUILDER_INSTALLTYPE="installer"
+fi
+if [ ! -e ${BUILDER_INSTALLTYPE}/${BUILDER_INSTALL}.json ] ; then
+   echo >&2 "ERROR: ${BUILDER_INSTALLTYPE}/${BUILDER_INSTALL}.json does not exist!"
+   exit 1
+fi
 (
    insert-json vmsetup/${BUILDER_VMSETUP}.json
    echo ","
-   echo "\"http_directory\": \"http\","
-   insert-json installer/${BUILDER_INSTALL}.json
+   if [ "${BUILDER_INSTALLTYPE}" == "installer" ] ; then
+      echo "\"http_directory\": \"http\","
+   fi
+   insert-json ${BUILDER_INSTALLTYPE}/${BUILDER_INSTALL}.json
 ) >>${JSONTMP}
 cat >>${JSONTMP} <<EOF
     }
@@ -473,7 +513,23 @@ cat >>${JSONTMP} <<EOF
   "provisioners": [
 EOF
 
-p=0
+if [ "${HYPERVISOR}" == "Docker" ] ; then
+   cat >>${JSONTMP} <<EOF
+       {
+         "type": "shell",
+         "execute_command": "{{.Vars}} bash '{{.Path}}'",
+         "script": "`realpath scripts/prepare-docker-container`",
+         "environment_vars": [ "FQDN=${FQDN}",
+                               "USER_NAME=${USER_NAME}",
+                               "USER_PASSWORD=${USER_PASSWORD}",
+                               "USER_REALNAME=${USER_REALNAME}" ]
+       }
+EOF
+   p=1
+else
+   p=0
+fi
+
 for provisioner in ${PROVISIONERS} ; do
    if [ ! -e scripts/${provisioner} ] ; then
       echo >&2 "ERROR: Provisioner scripts/${provisioner} does not exist!"
