Further FreeBSD configuration improvements.

diff --git a/make-vm b/make-vm
--- a/make-vm
+++ b/make-vm
@@ -536,15 +536,45 @@ else
 fi
 
 for provisioner in ${PROVISIONERS} ; do
-   if [ ! -e scripts/${provisioner} ] ; then
-      echo >&2 "ERROR: Provisioner scripts/${provisioner} does not exist!"
-      exit 1
+   found=0
+
+   # ------ File provisioner ------------------------------------------------
+   if [ -e files/${provisioner} ] ; then
+      found=1
+      let p=$p+1
+
+      cat files/${provisioner} | while read s destination ; do
+         if [[ ! "${s}" =~ ^([ \t]*#) ]] ; then
+            source="$(realpath files/${s})"
+            if [ ! -e "${source}" ] ; then
+               echo >&2 "ERROR: Cannot find source file ${source}!"
+               exit 1
+            fi
+
+            echo "S=${source}"
+            if [ $p -gt 1 ] ; then
+               echo "," >>${JSONTMP}
+            fi
+            cat >>${JSONTMP} <<EOF
+       {
+         "type": "file",
+         "source": "${source}",
+         "destination": "${destination}"
+       }
+EOF
+
+         fi
+      done
    fi
-   let p=$p+1
-   if [ $p -gt 1 ] ; then
-      echo "," >>${JSONTMP}
-   fi
-   cat >>${JSONTMP} <<EOF
+
+   # ------ Script provisioner ----------------------------------------------
+   if [ -e scripts/${provisioner} ] ; then
+      found=1
+      let p=$p+1
+      if [ $p -gt 1 ] ; then
+         echo "," >>${JSONTMP}
+      fi
+      cat >>${JSONTMP} <<EOF
        {
          "type": "shell",
          "execute_command": "echo '${USER_PASSWORD}' | {{.Vars}} sudo -S -E bash '{{.Path}}'",
@@ -562,7 +592,13 @@ for provisioner in ${PROVISIONERS} ; do
                                "BACKGROUND_DESKTOP=${BACKGROUND_DESKTOP}" ]
        }
 EOF
+   fi
 done
+
+   if [ ${found} -eq 0 ] ; then
+      echo >&2 "ERROR: Did not found provisioner ${provisioner}!"
+      exit 1
+   fi
 
 cat >>${JSONTMP} <<EOF
   ]
@@ -653,7 +689,6 @@ elif [ ${HYPERVISOR} == "QEMU" ] ; then
       sudo service vboxdrv stop || true
    fi
 fi
-
 
 echo "Running Packer:"
 cd "${OUTPUT_DIRECTORY}/${NAME}"
diff --git a/scripts/configure-kde-desktop b/scripts/configure-kde-desktop
--- a/scripts/configure-kde-desktop
+++ b/scripts/configure-kde-desktop
@@ -30,6 +30,35 @@ set -ex
 # - BACKGROUND_DESKTOP
 
 
+# ====== Make sure the background images are there ==========================
+if [ "${USER_NAME}"             == "" ] ||
+   [ "${BACKGROUND_SDDM}"       == "" ] ||
+   [ "${BACKGROUND_LOCKSCREEN}" == "" ] ||
+   [ "${BACKGROUND_DESKTOP}"    == "" ] ; then
+   echo >&2 "ERROR: Usage: env USER_NAME=<user> BACKGROUND_SDDM=<image> BACKGROUND_LOCKSCREEN=<image> BACKGROUND_DESKTOP=<image> $0"
+   echo >&2 "Example: env USER_NAME=nornetpp BACKGROUND_SDDM=/usr/share/desktop/Flåm-3840x2160-mosaic.jpeg BACKGROUND_LOCKSCREEN=/usr/share/desktop/Flåm-3840x2160-mosaic.jpeg BACKGROUND_DESKTOP=/usr/share/desktop/Flåm-3840x2160-plain.jpeg $0"
+   exit 1
+fi
+
+# If the background image files are not at their location, try to move them
+# from tmp/. They should have been placed there by the file provisioner.
+if [ ! -e "${BACKGROUND_SDDM}" ] ; then
+   dir="$(dirname ${BACKGROUND_SDDM})"
+   sudo mkdir -p "${dir}/"
+   sudo mv tmp/$(basename ${BACKGROUND_SDDM}) "${dir}/"
+fi
+if [ ! -e "${BACKGROUND_LOCKSCREEN}" ] ; then
+   dir="$(dirname ${BACKGROUND_LOCKSCREEN})"
+   sudo mkdir -p "${dir}/"
+   sudo mv tmp/$(basename ${BACKGROUND_LOCKSCREEN}) "${dir}/"
+fi
+if [ ! -e "${BACKGROUND_DESKTOP}" ] ; then
+   dir="$(dirname ${BACKGROUND_DESKTOP})"
+   sudo mkdir -p "${dir}/"
+   sudo mv tmp/$(basename ${BACKGROUND_DESKTOP}) "${dir}/"
+fi
+
+
 # ====== Make directories ===================================================
 mkdir -p /home/${USER_NAME}/.config
 mkdir -p /home/${USER_NAME}/.local
