Improved script.

diff --git a/proxmox-cleanup-templates b/proxmox-cleanup-templates
--- a/proxmox-cleanup-templates
+++ b/proxmox-cleanup-templates
@@ -21,6 +21,7 @@
 set -e
 
 
+# ====== Check arguments ====================================================
 dryRun=1
 if [ $# -gt 0 ] ; then
    if [ "$1" == "--really-remove" ] ; then
@@ -31,26 +32,60 @@ if [ $# -gt 0 ] ; then
    fi
 fi
 
-qm list | awk '
-{
+
+# ====== Identify templates and VMs for removal =============================
+echo -e "\x1b[34mLooking for VMs/templates to clean up ...\x1b[0m"
+qm list | sort -k2 -k1nr | awk '
+BEGIN {
+   lastName="";
+   lastID=-1;
+}
+
+/^[ ]*2[0-9][0-1][0-9][0-3][0-9][0-9][0-9][0-9] / {
    id=$1;
    name=$2;
    status=$3;
    if(id ~ /^2[0-9][0-1][0-9][0-3][0-9][0-9][0-9][0-9]$/ ) {
       if(status == "running") {
-         print("" id " " name " " status);
+         print "=> " name " is still running, but should be a not-running template!" | "cat 1>&2"
+         print id " " name " " status;
+      }
+      else if(status == "stopped") {
+         if(name == lastName) {
+            # This is an older version of the same template!
+            if(id < lastID) {
+               print "=> " name " (ID " id ") is older than " lastName " (ID " lastID ")" | "cat 1>&2"
+               print "" id " " name " " status;
+            }
+            else {
+               print "Something is wrong!" | "cat 1>&2"
+               exit 1;
+            }
+         }
+         else {
+            lastName = name;
+            lastID   = id;
+         }
       }
    }
 }
-' | \
-while read -r id name status ; do
-   if [ "${dryRun}" -eq 0 ] ; then
-      echo "Removing ${id} (${name}) with status \"${status}\" ..."
-      echo qm stop ${id}
-      echo qm destroy ${id}
-   else
-      echo "# Dry run only! Would remove ${id} (${name}) with status \"${status}\" ..."
-      echo qm stop ${id}
-      echo qm destroy ${id}   
-   fi
-done
+' | (
+   echo -e "\x1b[34mCleaning up obsolete VMs/templates ...\x1b[0m"
+   while read -r id name status ; do
+      if [[ ! "${id}" =~ ^2[0-9][0-1][0-9][0-3][0-9][0-9][0-9][0-9]$ ]] ; then
+         echo >&2 "ERROR: ID is not in the expected format! Something is wrong!"
+         exit 1
+      fi
+      if [ "${dryRun}" -eq 0 ] ; then
+         echo -e "\x1b[35mRemoving ${id} (${name}) with status \"${status}\" ...\x1b[0m"
+         echo -e "\x1b[36mqm stop ${id}\x1b[0m"
+         qm stop ${id}
+         echo -e "\x1b[36mqm destroy ${id}\x1b[0m"
+         qm destroy ${id}
+      else
+         echo -e "\x1b[35mDRY RUN ONLY: Would remove ${id} (${name}) with status \"${status}\" ...\x1b[0m"
+         echo -e "\x1b[36mqm stop ${id}\x1b[0m"
+         echo -e "\x1b[36mqm destroy ${id}\x1b[0m"
+      fi
+   done
+)
