Updated background generation scripts.

diff --git a/files/backgrounds/gimp-scripts/gs-caption b/files/backgrounds/gimp-scripts/gs-caption
--- a/files/backgrounds/gimp-scripts/gs-caption
+++ b/files/backgrounds/gimp-scripts/gs-caption
@@ -11,7 +11,7 @@
 # ==========================================================================
 #
 # GIMP Scripts
-# Copyright (C) 2013-2025 by Thomas Dreibholz
+# Copyright (C) 2013-2026 by Thomas Dreibholz
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -32,43 +32,66 @@
 set -eu
 
 
-# Example:
-# Make-Caption Caption.png "Caption Text" 1024 42 "Noto Sans Bold" 60
-# Make-Caption Caption.png "Caption Text" 1024 42 "Noto Sans Bold" 60 --foreground "#02266b" --background "#ffd700" --transparency 26
-
+# ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
 usage () {
    local exitCode="$1"
-   echo >&2 "Usage: $0 output_filename caption_text caption_width caption_height font font_size_percent [--foreground|-f color] [--background|-b color] [--transparency|-t percentage] [--verbose|-v] [--quiet|-q] [--help|-h]"
-   echo >&2 "Example: $0 Caption.png \"Caption Text\" 1024 42 \"Noto Sans Bold\" 60 \"#02266b\" \"#ffd700\" 26"
+   echo >&2 "Usage: $0 output_filename caption_width caption_height caption_text [-F|--font-name font] [-S|--font-size percentage] [-f|--foreground color] [-b|--background color] [|-t|--transparency percentage] [-w|--verbose] [-q|--quiet] [-h|--help]"
    exit "${exitCode}"
 }
 
 GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
 # shellcheck disable=SC2068
-options="$(${GETOPT} -o f:b:t:vqh --long foreground:,background:,transparency:,verbose,quiet,help -a -- "$@")"
+options="$(${GETOPT} -o F:S:f:b:t:wqh --long font-name:,font-size:,foreground:,background:,transparency:,verbose,quiet,help -a -- "$@")"
 eval set -- "${options}"
 
 COLOR_FOREGROUND="#02266b"   # Dark Blue
 COLOR_BACKGROUND="#ffd700"   # Gold
-TRANSPARENCY=25              # %
+FONT_NAME="Noto Sans Bold"
+FONT_SIZE="50"
+TRANSPARENCY=25              # in %
 VERBOSE=0
 while [ $# -gt 0 ] ; do
    case "$1" in
+      -F | --font-name)
+         FONT_NAME="$2"
+         shift 2
+         ;;
+      -S | --font-size)
+         FONT_SIZE="$2"
+         if [[ ! "${FONT_SIZE}" =~ ^[0-9]+$ ]] || [ "${FONT_SIZE}" -lt 1 ] || [ "${FONT_SIZE}" -gt 100 ] ; then
+            echo >&2 "ERROR: Invalid value ${FONT_SIZE} for -s|--font-size!"
+            exit 1
+         fi
+         shift 2
+         ;;
       -f | --foreground)
          COLOR_FOREGROUND="$2"
+         if [[ ! "${COLOR_FOREGROUND}" =~ ^#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$ ]] ; then
+            echo >&2 "ERROR: Invalid value ${COLOR_FOREGROUND} for -f|--foreground!"
+            exit 1
+         fi
          shift 2
          ;;
       -b | --background)
          COLOR_BACKGROUND="$2"
+         if [[ ! "${COLOR_BACKGROUND}" =~ ^#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$ ]] ; then
+            echo >&2 "ERROR: Invalid value ${COLOR_BACKGROUND} for -b|--background!"
+            exit 1
+         fi
          shift 2
          ;;
       -t | --transparency)
          TRANSPARENCY="$2"
+         if [[ ! "${TRANSPARENCY}" =~ ^[0-9]+$ ]] || [ "${TRANSPARENCY}" -lt 0 ] || [ "${TRANSPARENCY}" -gt 100 ]; then
+            echo >&2 "ERROR: Invalid value ${TRANSPARENCY} for -t|--transparency!"
+            exit 1
+         fi
+         TRANSPARENCY="$2"
          shift 2
          ;;
-      -v | --verbose)
+      -w | --verbose)
          VERBOSE=1
          shift
          ;;
@@ -89,41 +112,41 @@ while [ $# -gt 0 ] ; do
   esac
 done
 
-if [ $# -ne 6 ] ; then
+if [ $# -ne 4 ] ; then
    usage 1
 fi
 OUTPUT_FILENAME="$1"
-CAPTION_TEXT="$2"
-CAPTION_WIDTH=$3
-CAPTION_HEIGHT=$4
-FONT_NAME="$5"
-FONT_SIZE=$6
+CAPTION_WIDTH="$2"
+CAPTION_HEIGHT="$3"
+CAPTION_TEXT="$4"
 
-if [[ ! "${TRANSPARENCY}" =~ ^([0-9]+)$ ]] || [ "${TRANSPARENCY}" -lt 0 ] || [ "${TRANSPARENCY}" -gt 100 ] ; then
-   echo >&2 "ERROR: Invalid transparency value!"
-   exit 1
-fi
-if [[ ! "${CAPTION_WIDTH}" =~ ^([0-9]+)$ ]] ; then
+if [[ ! "${CAPTION_WIDTH}" =~ ^([0-9]+)$ ]] || [ "${CAPTION_WIDTH}" -lt 1 ]; then
    echo >&2 "ERROR: Invalid caption width!"
    exit 1
 fi
-if [[ ! "${CAPTION_HEIGHT}" =~ ^([0-9]+)$ ]] ; then
+if [[ ! "${CAPTION_HEIGHT}" =~ ^([0-9]+)$ ]] || [ "${CAPTION_HEIGHT}" -lt 1 ]; then
    echo >&2 "ERROR: Invalid caption height!"
    exit 1
 fi
 
 
-# ====== Obtain GIMP call options ===========================================
-if ! whereis gimp-console >/dev/null ; then
-   echo >&2 "ERROR: Gimp is not available!"
+# ====== Detect GIMP, and determine version-specific call options ===========
+GIMP_CONSOLE="$(which gimp-console 2>/dev/null || true)"
+if [ "${GIMP_CONSOLE}" == "" ] ; then
+   echo >&2 "ERROR: GIMP is not installed!"
+   echo >&2 "* Ubuntu:  sudo apt install -y gimp"
+   echo >&2 "* Fedora:  sudo dnf install -y gimp"
+   echo >&2 "* SuSE     sudo zypper install -y gimp"
+   echo >&2 "* Alpine:  sudo apk add gimp"
+   echo >&2 "* FreeBSD: sudo pkg install -y gimp3-app"
    exit 1
 fi
-GIMP_VERSION="$(LANG=C gimp-console --version | sed -e 's/GNU Image Manipulation Program version //')"
+GIMP_VERSION="$(LC_ALL=C.UTF-8 "${GIMP_CONSOLE}" --version | sed -e 's/GNU Image Manipulation Program version //')"
 if [[ "${GIMP_VERSION}" =~ ^[012] ]] ; then
-   # Gimp 2.x:
+   # GIMP 2.x:
    GIMP_OPTIONS="--new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
 else
-   # Gimp 3.x:
+   # GIMP 3.x:
    GIMP_OPTIONS="--quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
 fi
 
@@ -136,7 +159,7 @@ rm -f "${OUTPUT_FILENAME}"
 # shellcheck disable=SC2086
 ( cat <<EOF
 
-; Gimp 2.8 compatibility:
+; GIMP 2.8 compatibility:
 (cond ((not (defined? 'LAYER-MODE-NORMAL-LEGACY)) (define LAYER-MODE-NORMAL-LEGACY NORMAL-MODE)))
 (cond ((not (defined? 'FILL-BACKGROUND)) (define FILL-BACKGROUND BACKGROUND-FILL)))
 
@@ -155,16 +178,16 @@ rm -f "${OUTPUT_FILENAME}"
     (image (car (gimp-image-new captionWidth captionHeight RGB)))
     ; (layer1 (car (gimp-layer-new image captionWidth captionHeight RGBA-IMAGE "Layer 1" captionOpacity LAYER-MODE-NORMAL-LEGACY)))
     (layer1           (if (not (defined? 'gimp-image-get-active-layer))
-                         ; New Gimp 3.0 API:
+                         ; New GIMP 3.0 API:
                          (car (gimp-layer-new image "Layer 1" captionWidth captionHeight RGBA-IMAGE captionOpacity LAYER-MODE-NORMAL-LEGACY))
-                         ; Old Gimp 2.x API:
+                         ; Old GIMP 2.x API:
                          (car (gimp-layer-new image captionWidth captionHeight RGBA-IMAGE "Layer 1" captionOpacity LAYER-MODE-NORMAL-LEGACY))
                       ))
     ; (layer2 (car (gimp-layer-new image captionWidth captionHeight RGBA-IMAGE "Layer 2" 100 LAYER-MODE-NORMAL-LEGACY)))
     (layer2           (if (not (defined? 'gimp-image-get-active-layer))
-                         ; New Gimp 3.0 API:
+                         ; New GIMP 3.0 API:
                          (car (gimp-layer-new image "Layer 2" captionWidth captionHeight RGBA-IMAGE 100 LAYER-MODE-NORMAL-LEGACY))
-                         ; Old Gimp 2.x API:
+                         ; Old GIMP 2.x API:
                          (car (gimp-layer-new image captionWidth captionHeight RGBA-IMAGE "Layer 2" 100 LAYER-MODE-NORMAL-LEGACY))
                       ))
    )
@@ -186,14 +209,14 @@ rm -f "${OUTPUT_FILENAME}"
    (gimp-drawable-fill layer1 FILL-BACKGROUND)
 
    (if (defined? 'gimp-drawable-merge-new-filter)
-      (begin  ; New Gimp >= 3.0 API:
+      (begin  ; New GIMP >= 3.0 API:
          (set! theText (car (gimp-text-font image layer2 0 0 captionText 0 TRUE captionFontSize captionFont) ))
          (gimp-layer-set-offsets
             theText
             (/ (- captionWidth  (car (gimp-drawable-get-width  theText))) 2)
             (/ (- captionHeight (car (gimp-drawable-get-height theText))) 2))
       )
-      (begin  ; Old Gimp < 3.0 API:
+      (begin  ; Old GIMP < 3.0 API:
          (set! theText (car (gimp-text-fontname image layer2 0 0 captionText 0 TRUE captionFontSize PIXELS captionFont) ) )
          (gimp-layer-set-offsets
            theText
@@ -207,8 +230,8 @@ rm -f "${OUTPUT_FILENAME}"
 
    ; ------ Save result -----------------------------------------------------
    (if (defined? 'gimp-drawable-merge-new-filter)
-      (begin  ; New Gimp >= 3.0 API:
-         ; FIXME: This does not work when running in Gimp 2.x!
+      (begin  ; New GIMP >= 3.0 API:
+         ; FIXME: This does not work when running in GIMP 2.x!
          ; (file-png-export
          ;    #:run-mode         RUN-NONINTERACTIVE
          ;    #:image            image
@@ -227,7 +250,7 @@ rm -f "${OUTPUT_FILENAME}"
             outputFileName -1
             TRUE 6 TRUE FALSE TRUE TRUE FALSE TRUE)
       )
-      (begin  ; Old Gimp < 3.0 API:
+      (begin  ; Old GIMP < 3.0 API:
          (file-png-save2 RUN-NONINTERACTIVE image
             (car (gimp-image-get-active-layer image))
             outputFileName outputFileName
@@ -240,12 +263,12 @@ rm -f "${OUTPUT_FILENAME}"
 )
 (gimp-quit TRUE)
 EOF
-) | env LANG=C HOME=/tmp gimp-console ${GIMP_OPTIONS} 2>&1 | \
+) | env LC_ALL=C.UTF-8 HOME=/tmp "${GIMP_CONSOLE}" ${GIMP_OPTIONS} 2>&1 | \
 (
    if [ ${VERBOSE} -ne 0 ] ; then
       cat
    else
-      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
+      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
    fi
 )
 
diff --git a/files/backgrounds/gimp-scripts/gs-oilify b/files/backgrounds/gimp-scripts/gs-oilify
--- a/files/backgrounds/gimp-scripts/gs-oilify
+++ b/files/backgrounds/gimp-scripts/gs-oilify
@@ -11,7 +11,7 @@
 # ==========================================================================
 #
 # GIMP Scripts
-# Copyright (C) 2013-2025 by Thomas Dreibholz
+# Copyright (C) 2013-2026 by Thomas Dreibholz
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -32,27 +32,45 @@
 set -eu
 
 
-# Example:
-# Make-Background Demo-Fractal-8192x6144.png Background1.png
-
+# ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
 usage () {
    local exitCode="$1"
-   echo >&2 "Usage: $0 input_filename output_filename [--verbose|-v] [--quiet|-q] [--help|-h]"
-   echo >&2 "Example: $0 Demo-Fractal-8192x6144.png Background1.png"
+   echo >&2 "Usage: $0 input_filename output_filename [-S|--mask-size masksize] [-I|--intensity-mode on|off] [-w|--verbose] [-q|--quiet] [-h|--help]"
    exit "${exitCode}"
 }
 
 GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
 # shellcheck disable=SC2068
-options="$(${GETOPT} -o vqh --long verbose,quiet,help -a -- "$@")"
+options="$(${GETOPT} -o S:I:wqh --long mask-size:,intensity-mode:,verbose,quiet,help -a -- "$@")"
 eval set -- "${options}"
 
+MASK_SIZE=8
+INTENSITY_MODE="TRUE"
 VERBOSE=0
 while [ $# -gt 0 ] ; do
    case "$1" in
-      -v | --verbose)
+      -S | --mask-size)
+         MASK_SIZE="$2"
+         if [[ ! "${MASK_SIZE}" =~ ^([0-9]+)$ ]] ; then
+            echo >&2 "ERROR: Invalid value ${MASK_SIZE} for -S|--mask-size!"
+            exit 1
+         fi
+         shift 2
+         ;;
+      -I | --intensity-mode)
+         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+            INTENSITY_MODE="TRUE"
+         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+            INTENSITY_MODE="FALSE"
+         else
+            echo >&2 "ERROR: Invalid value $2 for -I|--intensity-mode!"
+            exit 1
+         fi
+         shift 2
+         ;;
+      -w | --verbose)
          VERBOSE=1
          shift
          ;;
@@ -85,17 +103,23 @@ if [ ! -f "${INPUT_FILENAME}" ] ; then
 fi
 
 
-# ====== Obtain GIMP call options ===========================================
-if ! whereis gimp-console >/dev/null ; then
-   echo >&2 "ERROR: Gimp is not available!"
+# ====== Detect GIMP, and determine version-specific call options ===========
+GIMP_CONSOLE="$(which gimp-console 2>/dev/null || true)"
+if [ "${GIMP_CONSOLE}" == "" ] ; then
+   echo >&2 "ERROR: GIMP is not installed!"
+   echo >&2 "* Ubuntu:  sudo apt install -y gimp"
+   echo >&2 "* Fedora:  sudo dnf install -y gimp"
+   echo >&2 "* SuSE     sudo zypper install -y gimp"
+   echo >&2 "* Alpine:  sudo apk add gimp"
+   echo >&2 "* FreeBSD: sudo pkg install -y gimp3-app"
    exit 1
 fi
-GIMP_VERSION="$(LANG=C gimp-console --version | sed -e 's/GNU Image Manipulation Program version //')"
+GIMP_VERSION="$(LC_ALL=C.UTF-8 "${GIMP_CONSOLE}" --version | sed -e 's/GNU Image Manipulation Program version //')"
 if [[ "${GIMP_VERSION}" =~ ^[012] ]] ; then
-   # Gimp 2.x:
+   # GIMP 2.x:
    GIMP_OPTIONS="--new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
 else
-   # Gimp 3.x:
+   # GIMP 3.x:
    GIMP_OPTIONS="--quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
 fi
 
@@ -111,73 +135,49 @@ rm -f "${OUTPUT_FILENAME}"
    ; ------ Initialise and load image ---------------------------------------
    ((inputFileName    "${INPUT_FILENAME}")
     (outputFileName   "${OUTPUT_FILENAME}")
+    (maskSize         ${MASK_SIZE})
+    (intensityMode    ${INTENSITY_MODE})
     (image            (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
     (imageType        (if (not (defined? 'gimp-image-get-active-layer))
-                         ; New Gimp 3.0 API:
+                         ; New GIMP 3.0 API:
                          (car (gimp-image-get-base-type image))
-                         ; Old Gimp 2.x API:
+                         ; Old GIMP 2.x API:
                          (car (gimp-image-base-type image)))
                       )
     (layer            (if (not (defined? 'gimp-image-get-active-layer))
-                         ; New Gimp 3.0 API:
+                         ; New GIMP 3.0 API:
                          (car (list (vector-ref (car (gimp-image-get-selected-layers image)) 0)))
-                         ; Old Gimp 2.x API:
+                         ; Old GIMP 2.x API:
                          (car (gimp-image-get-active-layer image)))
                       )
    )
 
    ; ------ Apply filter ----------------------------------------------------
    ; First, make sure that the image is RGB, not indexed color mode!
-   (if (defined? 'gimp-drawable-hue-saturation)
-      (begin  ; New Gimp > 2.8 API:
-         ; New Gimp > 2.8 API:
-         (gimp-drawable-hue-saturation layer HUE-RANGE-ALL 120.0 0 0 0)
-      )
-      (begin  ; Old Gimp <= 2.8 API:
-         (gimp-hue-saturation layer ALL-HUES 120.0 0 0)
+   (if (not (= RGB imageType))
+      (gimp-image-convert-rgb image))
+
+   ; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+   ; GEGL Oilify options: https://gegl.org/operations/gegl-oilify.html
+   ; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+
+   (cond( (not(defined? 'plug-in-mosaic))
+      ; New GIMP 3.0 API:
+      (gimp-drawable-merge-new-filter layer "gegl:oilify" 0 LAYER-INTENSITY_MODE-REPLACE 1.0
+          "mask-radius" (max 1 (/ maskSize 2))
+          "use-inten"   intensityMode
       )
    )
-
-   ; Step 2: Apply Bump Map effect
-   (if (defined? 'gimp-drawable-merge-new-filter)
-      (begin  ; New Gimp >= 3.0 API:
-        (gimp-drawable-merge-new-filter layer "gegl:bump-map" 0 LAYER-MODE-REPLACE 1.0
-            "azimuth"         30.0
-            "elevation"       45.0
-            "depth"           20.0
-            "offset-x"        0
-            "offset-y"        0
-            "waterlevel"      0.0
-            "ambient"         0.0
-            "compensate"      TRUE
-            "invert"          FALSE
-            "type"            "linear"
-        )
-      )
-      (begin  ; Old Gimp < 3.0 API:
-         (plug-in-bump-map RUN-NONINTERACTIVE image layer layer
-           30.0 45.0 20
-           0 0 0 0
-           TRUE FALSE 0)
-      )
-   )
-
-   ; Step 3: Darken the result a little bit
-   (if (defined? 'gimp-drawable-hue-saturation)
-      (begin  ; New Gimp > 2.8 API:
-         ; New Gimp > 2.8 API:
-         (gimp-drawable-hue-saturation layer HUE-RANGE-ALL 0 -15 0 0)
-      )
-      (begin  ; Old Gimp <= 2.8 API:
-         (gimp-hue-saturation layer ALL-HUES 0 -15 0)
-      )
-   )
-
+   (else
+      ; Old GIMP 2.x API:
+      (display maskSize) (newline)
+      (plug-in-oilify RUN-NONINTERACTIVE image layer maskSize intensityMode)
+   ))
 
    ; ------ Save result -----------------------------------------------------
    (if (defined? 'gimp-drawable-merge-new-filter)
-      (begin  ; New Gimp >= 3.0 API:
-         ; FIXME: This does not work when running in Gimp 2.x!
+      (begin  ; New GIMP >= 3.0 API:
+         ; FIXME: This does not work when running in GIMP 2.x!
          ; (file-png-export
          ;    #:run-mode         RUN-NONINTERACTIVE
          ;    #:image            image
@@ -196,7 +196,7 @@ rm -f "${OUTPUT_FILENAME}"
             outputFileName -1
             TRUE 6 TRUE FALSE TRUE TRUE FALSE TRUE)
       )
-      (begin  ; Old Gimp < 3.0 API:
+      (begin  ; Old GIMP < 3.0 API:
          (file-png-save2 RUN-NONINTERACTIVE image
             (car (gimp-image-get-active-layer image))
             outputFileName outputFileName
@@ -209,12 +209,12 @@ rm -f "${OUTPUT_FILENAME}"
 )
 (gimp-quit TRUE)
 EOF
-) | env LANG=C HOME=/tmp gimp-console ${GIMP_OPTIONS} 2>&1 | \
+) | env LC_ALL=C.UTF-8 HOME=/tmp "${GIMP_CONSOLE}" ${GIMP_OPTIONS} 2>&1 | \
 (
    if [ ${VERBOSE} -ne 0 ] ; then
       cat
    else
-      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
+      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
    fi
 )
 
diff --git a/files/backgrounds/gimp-scripts/gs-oldphoto b/files/backgrounds/gimp-scripts/gs-oldphoto
--- a/files/backgrounds/gimp-scripts/gs-oldphoto
+++ b/files/backgrounds/gimp-scripts/gs-oldphoto
@@ -11,7 +11,7 @@
 # ==========================================================================
 #
 # GIMP Scripts
-# Copyright (C) 2013-2025 by Thomas Dreibholz
+# Copyright (C) 2013-2026 by Thomas Dreibholz
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -32,61 +32,69 @@
 set -eu
 
 
-# Example:
-# Make-Mosaic Image1.jpeg Mosaic1.png 24 4 4 --type hexagons --surface rough
-# Make-Mosaic Image1.jpeg Mosaic2.png 32 4 2 --type octagons --surface smooth
-
+# ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
 usage () {
    local exitCode="$1"
-   echo >&2 "Usage: $0 input_filename output_filename tile_size tile_height tile_spacing [--type|-t squares|hexagons|octagons|triangles] [--surface|-s smooth|rough] [--neatness|-n neatness] [--lightdirection|-l direction] [-c|--colorvariation variation] [--verbose|-v] [--quiet|-q] [--help|-h]"
-   echo >&2 "Example: $0 Image.jpeg Mosaic.png 24 4 4 --type hexagons --surface rough"
+   echo >&2 "Usage: $0 input_filename output_filename [-D|--defocus on|off] [-B|--border-size border_size] [-S|--sepia on|off] [-M|--mottle on|off] [-w|--verbose] [-q|--quiet] [-h|--help]"
    exit "${exitCode}"
 }
 
 GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
 # shellcheck disable=SC2068
-options="$(${GETOPT} -o t:s:n:l:c:vqh --long type:,surface:,neatness:,lightdirection:,colorvariation:,verbose,quiet,help -a -- "$@")"
+options="$(${GETOPT} -o D:B:S:M:wqh --long defocus:,border-size:,sepia:,mottle:,verbose,quiet,help -a -- "$@")"
 eval set -- "${options}"
 
-TILE_NEATNESS=0.65
-TILE_TYPESTRING="hexagons"
-TILE_TYPE="6"
-TILE_SURFACE=0
-LIGHT_DIRECTION=135
-COLOR_VARIATION=0.2
+DEFOCUS="TRUE"
+BORDER_SIZE=10
+SEPIA="TRUE"
+MOTTLE="FALSE"
 VERBOSE=0
 while [ $# -gt 0 ] ; do
    case "$1" in
-      -t | --type)
-         TILE_TYPESTRING="$2"
-         shift 2
-         ;;
-      -s | --surface)
-         if [ "$2" == "smooth" ] ; then
-            TILE_SURFACE=0
-         elif [ "$2" == "rough" ] ; then
-            TILE_SURFACE=1
+      -D | --defocus)
+         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+            DEFOCUS="TRUE"
+         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+            DEFOCUS="FALSE"
          else
-            echo >&2 "Invalid tile surface: $2"
+            echo >&2 "ERROR: Invalid value $2 for -D|--defocus!"
             exit 1
          fi
          shift 2
          ;;
-      -n | --neatness)
-         TILE_NEATNESS="$2"
+      -B | --border-size)
+         BORDER_SIZE="$2"
+         if [[ ! "${BORDER_SIZE}" =~ ^[0-9]+$ ]] ; then
+            echo >&2 "ERROR: Invalid value ${BORDER_SIZE} for -B|--border-size!"
+            exit 1
+         fi
          shift 2
          ;;
-      -l | --lightdirection)
-         LIGHT_DIRECTION="$2"
+      -S | --sepia)
+         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+            SEPIA="TRUE"
+         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+            SEPIA="FALSE"
+         else
+            echo >&2 "ERROR: Invalid value $2 for -S|--sepia!"
+            exit 1
+         fi
          shift 2
          ;;
-      -c | --colorvariation)
-         COLOR_VARIATION="$2"
+      -M | --mottle)
+         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+            MOTTLE="TRUE"
+         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+            MOTTLE="FALSE"
+         else
+            echo >&2 "ERROR: Invalid value $2 for -M|--mottle!"
+            exit 1
+         fi
          shift 2
          ;;
-      -v | --verbose)
+      -w | --verbose)
          VERBOSE=1
          shift
          ;;
@@ -107,68 +115,35 @@ while [ $# -gt 0 ] ; do
   esac
 done
 
-if [ $# -ne 5 ] ; then
+if [ $# -ne 2 ] ; then
    usage 1
 fi
 INPUT_FILENAME="$1"
 OUTPUT_FILENAME="$2"
-TILE_SIZE=$3
-TILE_HEIGHT=$4
-TILE_SPACING=$5
 
 if [ ! -f "${INPUT_FILENAME}" ] ; then
    echo >&2 "ERROR: Input file ${INPUT_FILENAME} does not exist!"
    exit 1
 fi
-if [[ ! "${TILE_SIZE}" =~ ^[0-9]+$ ]] ; then
-   echo >&2 "ERROR: Invalid tile size!"
-   exit 1
-fi
-if [[ ! "${TILE_HEIGHT}" =~ ^[0-9]+$ ]] ; then
-   echo >&2 "ERROR: Invalid tile height!"
-   exit 1
-fi
-if [[ ! "${TILE_SPACING}" =~ ^[0-9]+$ ]] ; then
-   echo >&2 "ERROR: Invalid tile spacing!"
-   exit 1
-fi
-if [ "${TILE_TYPESTRING}" = "squares" ] ; then
-   TILE_TYPE=0
-elif [ "${TILE_TYPESTRING}" = "hexagons" ] ; then
-   TILE_TYPE=1
-elif [ "${TILE_TYPESTRING}" = "octagons" ] ; then
-   TILE_TYPE=2
-elif [ "${TILE_TYPESTRING}" = "triangles" ] ; then
-   TILE_TYPE=3
-else
-   echo >&2 "Invalid tile type ${TILE_TYPESTRING}!"
-   exit 1
-fi
-if [[ ! "${TILE_NEATNESS}" =~ ^([0-9]+|[0-9]+\.[0-9]*)$ ]] ; then
-   echo >&2 "ERROR: Invalid tile neatness ${TILE_NEATNESS}!"
-   exit 1
-fi
-if [[ ! "${COLOR_VARIATION}" =~ ^([0-9]+|[0-9]+\.[0-9]*)$ ]] ; then
-   echo >&2 "ERROR: Invalid color variation ${COLOR_VARIATION}!"
-   exit 1
-fi
-if [[ ! "${LIGHT_DIRECTION}" =~ ^([0-9]+)$ ]] ; then
-   echo >&2 "ERROR: Invalid light direction ${LIGHT_DIRECTION}!"
-   exit 1
-fi
 
 
-# ====== Obtain GIMP call options ===========================================
-if ! whereis gimp-console >/dev/null ; then
-   echo >&2 "ERROR: Gimp is not available!"
+# ====== Detect GIMP, and determine version-specific call options ===========
+GIMP_CONSOLE="$(which gimp-console 2>/dev/null || true)"
+if [ "${GIMP_CONSOLE}" == "" ] ; then
+   echo >&2 "ERROR: GIMP is not installed!"
+   echo >&2 "* Ubuntu:  sudo apt install -y gimp"
+   echo >&2 "* Fedora:  sudo dnf install -y gimp"
+   echo >&2 "* SuSE     sudo zypper install -y gimp"
+   echo >&2 "* Alpine:  sudo apk add gimp"
+   echo >&2 "* FreeBSD: sudo pkg install -y gimp3-app"
    exit 1
 fi
-GIMP_VERSION="$(LANG=C gimp-console --version | sed -e 's/GNU Image Manipulation Program version //')"
+GIMP_VERSION="$(LC_ALL=C.UTF-8 "${GIMP_CONSOLE}" --version | sed -e 's/GNU Image Manipulation Program version //')"
 if [[ "${GIMP_VERSION}" =~ ^[012] ]] ; then
-   # Gimp 2.x:
+   # GIMP 2.x:
    GIMP_OPTIONS="--new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
 else
-   # Gimp 3.x:
+   # GIMP 3.x:
    GIMP_OPTIONS="--quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
 fi
 
@@ -184,26 +159,21 @@ rm -f "${OUTPUT_FILENAME}"
    ; ------ Initialise and load image ---------------------------------------
    ((inputFileName    "${INPUT_FILENAME}")
     (outputFileName   "${OUTPUT_FILENAME}")
-    (tileType         ${TILE_TYPE})
-    (tileTypeString   "${TILE_TYPESTRING}")
-    (tileSize         ${TILE_SIZE})
-    (tileHeight       ${TILE_HEIGHT})
-    (tileSpacing      ${TILE_SPACING})
-    (tileNeatness     ${TILE_NEATNESS})
-    (tileSurface      ${TILE_SURFACE})
-    (lightDirection   ${LIGHT_DIRECTION})
-    (colorVariation   ${COLOR_VARIATION})
+    (defocus          ${DEFOCUS})
+    (borderSize       ${BORDER_SIZE})
+    (sepia            ${SEPIA})
+    (mottle           ${MOTTLE})
     (image            (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
     (imageType        (if (not (defined? 'gimp-image-get-active-layer))
-                         ; New Gimp 3.0 API:
+                         ; New GIMP 3.0 API:
                          (car (gimp-image-get-base-type image))
-                         ; Old Gimp 2.x API:
+                         ; Old GIMP 2.x API:
                          (car (gimp-image-base-type image)))
                       )
     (layer            (if (not (defined? 'gimp-image-get-active-layer))
-                         ; New Gimp 3.0 API:
+                         ; New GIMP 3.0 API:
                          (car (list (vector-ref (car (gimp-image-get-selected-layers image)) 0)))
-                         ; Old Gimp 2.x API:
+                         ; Old GIMP 2.x API:
                          (car (gimp-image-get-active-layer image)))
                       )
    )
@@ -213,37 +183,13 @@ rm -f "${OUTPUT_FILENAME}"
    (if (not (= RGB imageType))
       (gimp-image-convert-rgb image))
 
-   ; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-   ; GEGL Mosaic options: https://gegl.org/operations/gegl-mosaic.html
-   ; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-
-   (cond( (not(defined? 'plug-in-mosaic))
-      ; New Gimp 3.0 API:
-      (gimp-drawable-merge-new-filter layer "gegl:mosaic" 0 LAYER-MODE-REPLACE 1.0
-          "tile-size"       tileSize
-          "tile-height"     tileHeight
-          "tile-spacing"    tileSpacing
-          "tile-neatness"   tileNeatness
-          "antialiasing"    TRUE
-          "light-dir"       lightDirection
-          "color-variation" colorVariation
-          "tile-type"       tileTypeString
-          "tile-surface"    tileSurface
-          "seed"            0
-      )
-   )
-   (else
-      ; Old Gimp 2.x API:
-      (plug-in-mosaic RUN-NONINTERACTIVE image layer
-         tileSize tileHeight tileSpacing
-         tileNeatness TRUE lightDirection colorVariation TRUE TRUE
-         tileType tileSurface FALSE
-   )))
+   (script-fu-old-photo image layer
+                        defocus borderSize sepia mottle FALSE)
 
    ; ------ Save result -----------------------------------------------------
    (if (defined? 'gimp-drawable-merge-new-filter)
-      (begin  ; New Gimp >= 3.0 API:
-         ; FIXME: This does not work when running in Gimp 2.x!
+      (begin  ; New GIMP >= 3.0 API:
+         ; FIXME: This does not work when running in GIMP 2.x!
          ; (file-png-export
          ;    #:run-mode         RUN-NONINTERACTIVE
          ;    #:image            image
@@ -262,7 +208,7 @@ rm -f "${OUTPUT_FILENAME}"
             outputFileName -1
             TRUE 6 TRUE FALSE TRUE TRUE FALSE TRUE)
       )
-      (begin  ; Old Gimp < 3.0 API:
+      (begin  ; Old GIMP < 3.0 API:
          (file-png-save2 RUN-NONINTERACTIVE image
             (car (gimp-image-get-active-layer image))
             outputFileName outputFileName
@@ -275,12 +221,12 @@ rm -f "${OUTPUT_FILENAME}"
 )
 (gimp-quit TRUE)
 EOF
-) | env LANG=C HOME=/tmp gimp-console ${GIMP_OPTIONS} 2>&1 | \
+) | env LC_ALL=C.UTF-8 HOME=/tmp "${GIMP_CONSOLE}" ${GIMP_OPTIONS} 2>&1 | \
 (
    if [ ${VERBOSE} -ne 0 ] ; then
       cat
    else
-      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
+      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
    fi
 )
 
diff --git a/files/backgrounds/gimp-scripts/gs-test-gimp b/files/backgrounds/gimp-scripts/gs-test-gimp
--- a/files/backgrounds/gimp-scripts/gs-test-gimp
+++ b/files/backgrounds/gimp-scripts/gs-test-gimp
@@ -11,7 +11,7 @@
 # ==========================================================================
 #
 # GIMP Scripts
-# Copyright (C) 2013-2025 by Thomas Dreibholz
+# Copyright (C) 2013-2026 by Thomas Dreibholz
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -32,23 +32,24 @@
 set -eu
 
 
+# ###### Main program #######################################################
+
 # ====== Handle arguments ===================================================
 usage () {
    local exitCode="$1"
-   echo >&2 "Usage: $0 [--verbose|-v] [--quiet|-q] [--help|-h]"
-   echo >&2 "Example: $0 --verbose"
+   echo >&2 "Usage: $0 [-w|--verbose] [-q|--quiet] [-h|--help]"
    exit "${exitCode}"
 }
 
 GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
 # shellcheck disable=SC2068
-options="$(${GETOPT} -o vqh --long verbose,quiet,help -a -- "$@")"
+options="$(${GETOPT} -o wqh --long verbose,quiet,help -a -- "$@")"
 eval set -- "${options}"
 
 VERBOSE=0
 while [ $# -gt 0 ] ; do
    case "$1" in
-      -v | --verbose)
+      -w | --verbose)
          VERBOSE=1
          shift
          ;;
@@ -87,23 +88,29 @@ if [ "${GIMP3_DIRECTORY}" != "" ] ; then
    done
 
    # FIXME!
-   # Gimp 3.0 wastes a lot of CPU, for whatever reason. Just
+   # GIMP 3.0 wastes a lot of CPU, for whatever reason. Just
    # using 1 core seems to provide the best performance:
    echo "(num-processors 1)" >>"${GIMP3_DIRECTORY}/gimprc"
 fi
 
 
-# ====== Obtain GIMP call options ===========================================
-if ! whereis gimp-console >/dev/null ; then
-   echo >&2 "ERROR: Gimp is not available!"
+# ====== Detect GIMP, and determine version-specific call options ===========
+GIMP_CONSOLE="$(which gimp-console 2>/dev/null || true)"
+if [ "${GIMP_CONSOLE}" == "" ] ; then
+   echo >&2 "ERROR: GIMP is not installed!"
+   echo >&2 "* Ubuntu:  sudo apt install -y gimp"
+   echo >&2 "* Fedora:  sudo dnf install -y gimp"
+   echo >&2 "* SuSE     sudo zypper install -y gimp"
+   echo >&2 "* Alpine:  sudo apk add gimp"
+   echo >&2 "* FreeBSD: sudo pkg install -y gimp3-app"
    exit 1
 fi
-GIMP_VERSION="$(LANG=C gimp-console --version | sed -e 's/GNU Image Manipulation Program version //')"
+GIMP_VERSION="$(LC_ALL=C.UTF-8 "${GIMP_CONSOLE}" --version | sed -e 's/GNU Image Manipulation Program version //')"
 if [[ "${GIMP_VERSION}" =~ ^[012] ]] ; then
-   # Gimp 2.x:
+   # GIMP 2.x:
    GIMP_OPTIONS="--new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
 else
-   # Gimp 3.x:
+   # GIMP 3.x:
    GIMP_OPTIONS="--quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
 fi
 
@@ -116,11 +123,11 @@ GIMP_OPTIONS="${GIMP_OPTIONS} --no-fonts --no-data"
 ( cat <<EOF
 (gimp-quit TRUE)
 EOF
-) | env LANG=C HOME=/tmp gimp-console ${GIMP_OPTIONS} 2>&1 | \
+) | env LC_ALL=C.UTF-8 HOME=/tmp "${GIMP_CONSOLE}" ${GIMP_OPTIONS} 2>&1 | \
 (
    if [ ${VERBOSE} -ne 0 ] ; then
       cat
    else
-      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
+      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
    fi
 )
