Updated GIMP scripts.

diff --git a/files/backgrounds/gimp-scripts/gs-oldphoto b/files/backgrounds/gimp-scripts/gs-oldphoto
--- a/files/backgrounds/gimp-scripts/gs-oldphoto
+++ b/files/backgrounds/gimp-scripts/gs-oldphoto
@@ -42,7 +42,7 @@ usage () {
 
 # ###### Version ############################################################
 version () {
-   echo "gs-oldphoto 2.7.2"
+   echo "gs-oldphoto 2.7.10"
    exit 0
 }
 
@@ -55,7 +55,27 @@ if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1]
    echo "ERROR: Bash 4.2 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
    exit 1
 fi
-GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+UNAME="$(uname)"
+case "${UNAME}" in
+   FreeBSD)
+      GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt || true)"
+      ;;
+   NetBSD)
+      GETOPT="$(PATH="/usr/pkg/bin:${PATH}" command -v getopt || true)"
+      ;;
+   OpenBSD)
+      GETOPT="$(command -v gnugetopt || true)"
+      ;;
+   SunOS)
+      GETOPT="$(PATH="/usr/gnu/bin:${PATH}" command -v getopt || true)"
+      ;;
+   Darwin)
+      GETOPT="$(env PATH="/opt/homebrew/opt/gnu-getopt/bin:${PATH}" command -v getopt || true)"
+      ;;
+   *)
+      GETOPT="$(command -v getopt || true)"
+      ;;
+esac
 if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
    echo >&2 "ERROR: Enhanced/GNU getopt is required!"
    exit 1
@@ -156,14 +176,17 @@ fi
 
 
 # ====== Detect GIMP, and determine version-specific call options ===========
-GIMP_CONSOLE="$(command -v gimp-console || true)"
+GIMP_CONSOLE="$(command -v gimp-console || command -v /Applications/GIMP.app/Contents/MacOS/gimp-console-3 || true)"
 if [ "${GIMP_CONSOLE}" == "" ] ; then
-   echo >&2 "ERROR: GIMP is not installed!"
-   echo >&2 "* Ubuntu:  sudo apt install -y gimp"
-   echo >&2 "* Fedora:  sudo dnf install -y gimp"
-   echo >&2 "* SuSE     sudo zypper install -y gimp"
-   echo >&2 "* Alpine:  sudo apk add gimp"
-   echo >&2 "* FreeBSD: sudo pkg install -y gimp3-app"
+   echo >&2 "ERROR: GIMP is not installed! Try:"
+   echo >&2 " * Ubuntu/Debian: sudo apt install -y gimp"
+   echo >&2 " * Fedora:        sudo dnf install -y gimp"
+   echo >&2 " * SuSE           sudo zypper install -y gimp"
+   echo >&2 " * Alpine:        sudo apk add gimp"
+   echo >&2 " * FreeBSD:       sudo pkg install -y gimp3-app"
+   echo >&2 " * NetBSD:        sudo pkgin -y install gimp"
+   echo >&2 " * OpenBSD:       sudo pkg_add gimp"
+   echo >&2 " * Apple:         brew install gimp"
    exit 1
 fi
 GIMP_VERSION="$(LC_ALL=C.UTF-8 "${GIMP_CONSOLE}" --version | sed -e 's/GNU Image Manipulation Program version //')"
@@ -260,7 +283,7 @@ EOF
    if [ ${VERBOSE} -ne 0 ] ; then
       cat
    else
-      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
+      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Warning: Unknown input_id|^Failed to parse tag cache|^Please use named arguments:|^script quit with code:|^GIMP is started|^$" || true
    fi
 )
 
