Updated background scripts.

diff --git a/files/backgrounds/gimp-scripts/Make-Background b/files/backgrounds/gimp-scripts/Make-Background
--- a/files/backgrounds/gimp-scripts/Make-Background
+++ b/files/backgrounds/gimp-scripts/Make-Background
@@ -19,7 +19,7 @@
 # Contact: thomas.dreibholz@gmail.com
 
 # Bash options:
-set -e
+set -eu
 
 
 # Example:
@@ -27,49 +27,190 @@ set -e
 
 
 # ====== Handle arguments ===================================================
+usage () {
+   local exitCode="$1"
+   echo >&2 "Usage: $0 input_filename output_filename [--verbose|-v] [--quiet|-q] [--help|-h]"
+   echo >&2 "Example: $0 Demo-Fractal-8192x6144.png Background1.png"
+   exit "${exitCode}"
+}
+
+GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
+# shellcheck disable=SC2068
+options="$(${GETOPT} -o vqh --long verbose,quiet,help -a -- "$@")"
+eval set -- "${options}"
+
+VERBOSE=0
+while [ $# -gt 0 ] ; do
+   case "$1" in
+      -v | --verbose)
+         VERBOSE=1
+         shift
+         ;;
+      -q | --quiet)
+         VERBOSE=0
+         shift
+         ;;
+      -h | --help)
+         usage 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         usage 1
+         ;;
+  esac
+done
+
 if [ $# -lt 2 ] ; then
-   echo >&2 "Usage: $0 input_filename output_filename"
+   usage 1
+fi
+INPUT_FILENAME="$1"
+OUTPUT_FILENAME="$2"
+
+if [ ! -f "${INPUT_FILENAME}" ] ; then
+   echo >&2 "ERROR: Input file ${INPUT_FILENAME} does not exist!"
    exit 1
 fi
-INPUTFILENAME="$1"
-OUTPUTFILENAME="$2"
-# if [ $# -gt 3 ] ; then
-#    COLORSCHEME="$4"
-# fi
+
+
+# ====== Obtain GIMP call options ===========================================
+if ! whereis gimp-console >/dev/null ; then
+   echo >&2 "ERROR: Gimp is not available!"
+   exit 1
+fi
+GIMP_VERSION="$(LANG=C gimp-console --version | sed -e 's/GNU Image Manipulation Program version //')"
+if [[ "${GIMP_VERSION}" =~ ^[012] ]] ; then
+   # Gimp 2.x:
+   GIMP_OPTIONS="--new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
+else
+   # Gimp 3.x:
+   GIMP_OPTIONS="--quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
+fi
+
+# This script does not use fonts, or gradients/palettes/brushes:
+GIMP_OPTIONS="${GIMP_OPTIONS} --no-fonts --no-data"
 
 
 # ====== Call GIMP ==========================================================
-rm -f "$OUTPUTFILENAME"
+rm -f "${OUTPUT_FILENAME}"
+# shellcheck disable=SC2086
 ( cat <<EOF
 (let*
-   ((inputFileName    "$INPUTFILENAME")
-    (outputFileName   "$OUTPUTFILENAME")
-    (image (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
-    (drawable (car (gimp-image-get-active-layer image)))
+   ; ------ Initialise and load image ---------------------------------------
+   ((inputFileName    "${INPUT_FILENAME}")
+    (outputFileName   "${OUTPUT_FILENAME}")
+    (image            (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
+    (imageType        (if (not (defined? 'gimp-image-get-active-layer))
+                         ; New Gimp 3.0 API:
+                         (car (gimp-image-get-base-type image))
+                         ; Old Gimp 2.x API:
+                         (car (gimp-image-base-type image)))
+                      )
+    (layer            (if (not (defined? 'gimp-image-get-active-layer))
+                         ; New Gimp 3.0 API:
+                         (car (list (vector-ref (car (gimp-image-get-selected-layers image)) 0)))
+                         ; Old Gimp 2.x API:
+                         (car (gimp-image-get-active-layer image)))
+                      )
    )
-   ; ------------------------------------------------------------------------
-   ; First, make sure that the image is RGB, not indexed color mode!
-   (if (not (= RGB (car (gimp-image-base-type image))))
-             (gimp-image-convert-rgb image))
 
-   ; Change colours
-   (gimp-hue-saturation drawable ALL-HUES 120 0 0)
-   ; Bump Map
-   (plug-in-bump-map RUN-NONINTERACTIVE image drawable drawable
-      30.0 45.0 20
-      0 0 0 0
-      TRUE FALSE 0)
-   ; Darken it a little bit
-   (gimp-hue-saturation drawable ALL-HUES 0 -15 0)
-   ; ------------------------------------------------------------------------
-   (file-png-save2 RUN-NONINTERACTIVE image drawable outputFileName outputFileName TRUE 9 TRUE TRUE FALSE TRUE TRUE FALSE TRUE)
+   ; ------ Apply filter ----------------------------------------------------
+   ; First, make sure that the image is RGB, not indexed color mode!
+   (if (defined? 'gimp-drawable-hue-saturation)
+      (begin  ; New Gimp > 2.8 API:
+         ; New Gimp > 2.8 API:
+         (gimp-drawable-hue-saturation layer HUE-RANGE-ALL 120.0 0 0 0)
+      )
+      (begin  ; Old Gimp <= 2.8 API:
+         (gimp-hue-saturation layer ALL-HUES 120.0 0 0)
+      )
+   )
+
+   ; Step 2: Apply Bump Map effect
+   (if (defined? 'gimp-drawable-merge-new-filter)
+      (begin  ; New Gimp >= 3.0 API:
+        (gimp-drawable-merge-new-filter layer "gegl:bump-map" 0 LAYER-MODE-REPLACE 1.0
+            "azimuth"         30.0
+            "elevation"       45.0
+            "depth"           20.0
+            "offset-x"        0
+            "offset-y"        0
+            "waterlevel"      0.0
+            "ambient"         0.0
+            "compensate"      TRUE
+            "invert"          FALSE
+            "type"            "linear"
+        )
+      )
+      (begin  ; Old Gimp < 3.0 API:
+         (plug-in-bump-map RUN-NONINTERACTIVE image layer layer
+           30.0 45.0 20
+           0 0 0 0
+           TRUE FALSE 0)
+      )
+   )
+
+   ; Step 3: Darken the result a little bit
+   (if (defined? 'gimp-drawable-hue-saturation)
+      (begin  ; New Gimp > 2.8 API:
+         ; New Gimp > 2.8 API:
+         (gimp-drawable-hue-saturation layer HUE-RANGE-ALL 0 -15 0 0)
+      )
+      (begin  ; Old Gimp <= 2.8 API:
+         (gimp-hue-saturation layer ALL-HUES 0 -15 0)
+      )
+   )
+
+
+   ; ------ Save result -----------------------------------------------------
+   (if (defined? 'gimp-drawable-merge-new-filter)
+      (begin  ; New Gimp >= 3.0 API:
+         ; FIXME: This does not work when running in Gimp 2.x!
+         ; (file-png-export
+         ;    #:run-mode         RUN-NONINTERACTIVE
+         ;    #:image            image
+         ;    #:file             outputFileName
+         ;    #:options          -1
+         ;    #:interlaced       TRUE
+         ;    #:compression      6
+         ;    #:bkgd             TRUE
+         ;    #:offs             FALSE
+         ;    #:phys             TRUE
+         ;    #:time             TRUE
+         ;    #:save-transparent FALSE
+         ;    #:optimize-palette TRUE
+         ; )
+         (file-png-export RUN-NONINTERACTIVE image
+            outputFileName -1
+            TRUE 6 TRUE FALSE TRUE TRUE FALSE TRUE)
+      )
+      (begin  ; Old Gimp < 3.0 API:
+         (file-png-save2 RUN-NONINTERACTIVE image
+            (car (gimp-image-get-active-layer image))
+            outputFileName outputFileName
+            TRUE 6 TRUE TRUE FALSE TRUE TRUE FALSE TRUE)
+      )
+   )
+
+   ; ------ Clean up --------------------------------------------------------
+   (gimp-image-delete image)
 )
 (gimp-quit TRUE)
 EOF
-) | env LANG=C HOME=/tmp gimp --new-instance --no-interface --no-splash --batch - 2>&1 | \
-       ( grep -vE "^ts>|(#t)|^Copyright|^Welcome|GLib-GObject-WARNING|GEGL-CRITICAL|missing babl fast path|Missing fast-path babl|accelerates GEGL|first occurance of formats|programmatically by bab|GeglBuffers leaked|Failed to parse tag cache|^$" || true )
+) | env LANG=C HOME=/tmp gimp-console ${GIMP_OPTIONS} 2>&1 | \
+(
+   if [ ${VERBOSE} -ne 0 ] ; then
+      cat
+   else
+      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
+   fi
+)
 
-if [ ! -e "$OUTPUTFILENAME" ] ; then
-   echo >&2 "ERROR: $OUTPUTFILENAME has not been produced. Something went wrong!"
+
+# ====== Check result =======================================================
+if [ ! -e "${OUTPUT_FILENAME}" ] ; then
+   echo >&2 "ERROR: ${OUTPUT_FILENAME} has not been produced. Something went wrong!"
    exit 1
 fi
diff --git a/files/backgrounds/gimp-scripts/Make-Caption b/files/backgrounds/gimp-scripts/Make-Caption
--- a/files/backgrounds/gimp-scripts/Make-Caption
+++ b/files/backgrounds/gimp-scripts/Make-Caption
@@ -19,84 +19,229 @@
 # Contact: thomas.dreibholz@gmail.com
 
 # Bash options:
-set -e
+set -eu
 
 
 # Example:
-# Make-Caption Caption.png Caption.input 1024 42 "Noto Sans Bold" 60
-# Make-Caption Caption.png Caption.input 1024 42 "Noto Sans Bold" 60 "#02266b" "#ffd700" 26
+# Make-Caption Caption.png "Caption Text" 1024 42 "Noto Sans Bold" 60
+# Make-Caption Caption.png "Caption Text" 1024 42 "Noto Sans Bold" 60 --foreground "#02266b" --background "#ffd700" --transparency 26
 
 
 # ====== Handle arguments ===================================================
-if [ $# -lt 6 ] ; then
-   echo >&2 "Usage: $0 output_filename caption_text caption_width caption_height font font_size_percent [foreground [background [transparency]]]"
-   exit 1
-fi
-OUTPUTFILENAME="$1"
-CAPTION_TEXT="$2"
-CAPTION_WIDTH=$3
-CAPTION_HEIGHT=$4
-FONT="$5"
-FONT_SIZE=$6
+usage () {
+   local exitCode="$1"
+   echo >&2 "Usage: $0 output_filename caption_text caption_width caption_height font font_size_percent [--foreground|-f color] [--background|-b color] [--transparency|-t percentage] [--verbose|-v] [--quiet|-q] [--help|-h]"
+   echo >&2 "Example: $0 Caption.png \"Caption Text\" 1024 42 \"Noto Sans Bold\" 60 \"#02266b\" \"#ffd700\" 26"
+   exit "${exitCode}"
+}
+
+GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
+# shellcheck disable=SC2068
+options="$(${GETOPT} -o f:b:t:vqh --long foreground:,background:,transparency:,verbose,quiet,help -a -- "$@")"
+eval set -- "${options}"
 
 COLOR_FOREGROUND="#02266b"   # Dark Blue
 COLOR_BACKGROUND="#ffd700"   # Gold
 TRANSPARENCY=25              # %
-if [ $# -gt 6 ] ; then
-   COLOR_FOREGROUND="$7"
-   if [ $# -gt 7 ] ; then
-      COLOR_BACKGROUND="$8"
-      if [ $# -gt 8 ] ; then
-         TRANSPARENCY="$9"
-      fi
-   fi
+VERBOSE=0
+while [ $# -gt 0 ] ; do
+   case "$1" in
+      -f | --foreground)
+         COLOR_FOREGROUND="$2"
+         shift 2
+         ;;
+      -b | --background)
+         COLOR_BACKGROUND="$2"
+         shift 2
+         ;;
+      -t | --transparency)
+         TRANSPARENCY="$2"
+         shift 2
+         ;;
+      -v | --verbose)
+         VERBOSE=1
+         shift
+         ;;
+      -q | --quiet)
+         VERBOSE=0
+         shift
+         ;;
+      -h | --help)
+         usage 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         usage 1
+         ;;
+  esac
+done
+
+if [ $# -ne 6 ] ; then
+   usage 1
+fi
+OUTPUT_FILENAME="$1"
+CAPTION_TEXT="$2"
+CAPTION_WIDTH=$3
+CAPTION_HEIGHT=$4
+FONT_NAME="$5"
+FONT_SIZE=$6
+
+if [[ ! "${TRANSPARENCY}" =~ ^([0-9]+)$ ]] || [ "${TRANSPARENCY}" -lt 0 ] || [ "${TRANSPARENCY}" -gt 100 ] ; then
+   echo >&2 "ERROR: Invalid transparency value!"
+   exit 1
+fi
+if [[ ! "${CAPTION_WIDTH}" =~ ^([0-9]+)$ ]] ; then
+   echo >&2 "ERROR: Invalid caption width!"
+   exit 1
+fi
+if [[ ! "${CAPTION_HEIGHT}" =~ ^([0-9]+)$ ]] ; then
+   echo >&2 "ERROR: Invalid caption height!"
+   exit 1
 fi
 
 
+# ====== Obtain GIMP call options ===========================================
+if ! whereis gimp-console >/dev/null ; then
+   echo >&2 "ERROR: Gimp is not available!"
+   exit 1
+fi
+GIMP_VERSION="$(LANG=C gimp-console --version | sed -e 's/GNU Image Manipulation Program version //')"
+if [[ "${GIMP_VERSION}" =~ ^[012] ]] ; then
+   # Gimp 2.x:
+   GIMP_OPTIONS="--new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
+else
+   # Gimp 3.x:
+   GIMP_OPTIONS="--quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
+fi
+
+# This script does not use gradients/palettes/brushes:
+GIMP_OPTIONS="${GIMP_OPTIONS} --no-data"
+
+
 # ====== Call GIMP ==========================================================
-rm -f "$OUTPUTFILENAME"
+rm -f "${OUTPUT_FILENAME}"
+# shellcheck disable=SC2086
 ( cat <<EOF
+
+; Gimp 2.8 compatibility:
+(cond ((not (defined? 'LAYER-MODE-NORMAL-LEGACY)) (define LAYER-MODE-NORMAL-LEGACY NORMAL-MODE)))
+(cond ((not (defined? 'FILL-BACKGROUND)) (define FILL-BACKGROUND BACKGROUND-FILL)))
+
 (let*
-   ((outputFileName   "$OUTPUTFILENAME")
-    (captionText      "$CAPTION_TEXT")
-    (captionWidth     $CAPTION_WIDTH)
-    (captionHeight    $CAPTION_HEIGHT)
-    (captionFont      "$FONT")
-    (captionFontSize  (/ (* $FONT_SIZE captionHeight) 100))
-    (captionOpacity   (- 100 $TRANSPARENCY))
-    (captionFGColor   "$COLOR_FOREGROUND")
-    (captionBGColor   "$COLOR_BACKGROUND")
+   ; ------ Initialise ------------------------------------------------------
+   ((outputFileName   "${OUTPUT_FILENAME}")
+    (captionText      "${CAPTION_TEXT}")
+    (captionWidth     ${CAPTION_WIDTH})
+    (captionHeight    ${CAPTION_HEIGHT})
+    (captionFont)
+    (captionFontSize  (/ (* ${FONT_SIZE} captionHeight) 100))
+    (captionOpacity   (- 100 ${TRANSPARENCY}))
+    (captionFGColor   "${COLOR_FOREGROUND}")
+    (captionBGColor   "${COLOR_BACKGROUND}")
     (theText)
-    (drawable)
     (image (car (gimp-image-new captionWidth captionHeight RGB)))
-    (layer1 (car (gimp-layer-new image captionWidth captionHeight RGBA-IMAGE "Layer 1" captionOpacity NORMAL-MODE)))
-    (layer2 (car (gimp-layer-new image captionWidth captionHeight RGBA-IMAGE "Layer 2" 100 NORMAL-MODE)))
+    ; (layer1 (car (gimp-layer-new image captionWidth captionHeight RGBA-IMAGE "Layer 1" captionOpacity LAYER-MODE-NORMAL-LEGACY)))
+    (layer1           (if (not (defined? 'gimp-image-get-active-layer))
+                         ; New Gimp 3.0 API:
+                         (car (gimp-layer-new image "Layer 1" captionWidth captionHeight RGBA-IMAGE captionOpacity LAYER-MODE-NORMAL-LEGACY))
+                         ; Old Gimp 2.x API:
+                         (car (gimp-layer-new image captionWidth captionHeight RGBA-IMAGE "Layer 1" captionOpacity LAYER-MODE-NORMAL-LEGACY))
+                      ))
+    ; (layer2 (car (gimp-layer-new image captionWidth captionHeight RGBA-IMAGE "Layer 2" 100 LAYER-MODE-NORMAL-LEGACY)))
+    (layer2           (if (not (defined? 'gimp-image-get-active-layer))
+                         ; New Gimp 3.0 API:
+                         (car (gimp-layer-new image "Layer 2" captionWidth captionHeight RGBA-IMAGE 100 LAYER-MODE-NORMAL-LEGACY))
+                         ; Old Gimp 2.x API:
+                         (car (gimp-layer-new image captionWidth captionHeight RGBA-IMAGE "Layer 2" 100 LAYER-MODE-NORMAL-LEGACY))
+                      ))
    )
-   ; ------------------------------------------------------------------------
-   (gimp-image-add-layer image layer1 0)
-   (gimp-image-add-layer image layer2 0)
+
+   (if (not (defined? 'gimp-image-get-active-layer))
+      (set! captionFont (car (gimp-font-get-by-name "${FONT_NAME}")))
+      (set! captionFont "${FONT_NAME}"))
+   ; (newline) (display "captionFont=") (display captionFont) (newline)
+   (if (and (not (defined? 'gimp-image-get-active-layer)) (= captionFont -1)) (
+      (gimp-message "ERROR: Font \"${FONT_NAME}\" is not available! Check installed fonts with fc-list!")
+      (quit FALSE)
+   ))
+
+   ; ------ Generate caption ------------------------------------------------
+   (gimp-image-insert-layer image layer1 -1 0)
+   (gimp-image-insert-layer image layer2 -1 0)
    (gimp-context-set-background captionBGColor)
    (gimp-context-set-foreground captionFGColor)
-   (gimp-drawable-fill layer1 BACKGROUND-FILL)
+   (gimp-drawable-fill layer1 FILL-BACKGROUND)
 
-   (set! theText (car (gimp-text-fontname image layer2 0 0 captionText 0 TRUE captionFontSize PIXELS captionFont) ) )
-   (gimp-layer-set-offsets
-      theText
-      (/ (- captionWidth  (car (gimp-drawable-width  theText))) 2)
-      (/ (- captionHeight (car (gimp-drawable-height theText))) 2))
+   (if (defined? 'gimp-drawable-merge-new-filter)
+      (begin  ; New Gimp >= 3.0 API:
+         (set! theText (car (gimp-text-font image layer2 0 0 captionText 0 TRUE captionFontSize captionFont) ))
+         (gimp-layer-set-offsets
+            theText
+            (/ (- captionWidth  (car (gimp-drawable-get-width  theText))) 2)
+            (/ (- captionHeight (car (gimp-drawable-get-height theText))) 2))
+      )
+      (begin  ; Old Gimp < 3.0 API:
+         (set! theText (car (gimp-text-fontname image layer2 0 0 captionText 0 TRUE captionFontSize PIXELS captionFont) ) )
+         (gimp-layer-set-offsets
+           theText
+           (/ (- captionWidth  (car (gimp-drawable-width  theText))) 2)
+           (/ (- captionHeight (car (gimp-drawable-height theText))) 2))
+      )
+   )
 
    (gimp-image-merge-visible-layers image CLIP-TO-IMAGE)
    ; (gimp-display-new image)
-   ; ------------------------------------------------------------------------
-   (set! drawable (car (gimp-image-get-active-layer image)))
-   (file-png-save2 RUN-NONINTERACTIVE image drawable outputFileName outputFileName TRUE 9 TRUE TRUE FALSE TRUE TRUE FALSE TRUE)
+
+   ; ------ Save result -----------------------------------------------------
+   (if (defined? 'gimp-drawable-merge-new-filter)
+      (begin  ; New Gimp >= 3.0 API:
+         ; FIXME: This does not work when running in Gimp 2.x!
+         ; (file-png-export
+         ;    #:run-mode         RUN-NONINTERACTIVE
+         ;    #:image            image
+         ;    #:file             outputFileName
+         ;    #:options          -1
+         ;    #:interlaced       TRUE
+         ;    #:compression      6
+         ;    #:bkgd             TRUE
+         ;    #:offs             FALSE
+         ;    #:phys             TRUE
+         ;    #:time             TRUE
+         ;    #:save-transparent FALSE
+         ;    #:optimize-palette TRUE
+         ; )
+         (file-png-export RUN-NONINTERACTIVE image
+            outputFileName -1
+            TRUE 6 TRUE FALSE TRUE TRUE FALSE TRUE)
+      )
+      (begin  ; Old Gimp < 3.0 API:
+         (file-png-save2 RUN-NONINTERACTIVE image
+            (car (gimp-image-get-active-layer image))
+            outputFileName outputFileName
+            TRUE 6 TRUE TRUE FALSE TRUE TRUE FALSE TRUE)
+      )
+   )
+
+   ; ------ Clean up --------------------------------------------------------
+   (gimp-image-delete image)
 )
 (gimp-quit TRUE)
 EOF
-) | env LANG=C HOME=/tmp gimp --new-instance --no-interface --no-splash --batch - 2>&1 | \
-       ( grep -vE "^ts>|(#t)|^Copyright|^Welcome|GLib-GObject-WARNING|GEGL-gegl-operation.c-WARNING|GEGL-CRITICAL|missing babl fast path|Missing fast-path babl|accelerates GEGL|first occurance of formats|programmatically by bab|GeglBuffers leaked|Failed to parse tag cache|^$" || true )
+) | env LANG=C HOME=/tmp gimp-console ${GIMP_OPTIONS} 2>&1 | \
+(
+   if [ ${VERBOSE} -ne 0 ] ; then
+      cat
+   else
+      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
+   fi
+)
 
-if [ ! -e "$OUTPUTFILENAME" ] ; then
-   echo >&2 "ERROR: $OUTPUTFILENAME has not been produced. Something went wrong!"
+
+# ====== Check result =======================================================
+if [ ! -e "${OUTPUT_FILENAME}" ] ; then
+   echo >&2 "ERROR: ${OUTPUT_FILENAME} has not been produced. Something went wrong!"
    exit 1
 fi
diff --git a/files/backgrounds/gimp-scripts/Make-Cloth b/files/backgrounds/gimp-scripts/Make-Cloth
--- a/files/backgrounds/gimp-scripts/Make-Cloth
+++ b/files/backgrounds/gimp-scripts/Make-Cloth
@@ -19,47 +19,175 @@
 # Contact: thomas.dreibholz@gmail.com
 
 # Bash options:
-set -e
+set -eu
 
 
 # Example:
-# Make-Cloth Image.jpeg Cloth.png 6
+# Make-Cloth Image1.jpeg Cloth1.png
+# Make-Cloth Image1.jpeg Cloth2.png --depth 8
 
 
 # ====== Handle arguments ===================================================
-if [ $# -lt 2 ] ; then
-   echo >&2 "Usage: $0 input_filename output_filename [depth]"
+usage () {
+   local exitCode="$1"
+   echo >&2 "Usage: $0 input_filename output_filename [--depth|-d depth] [--verbose|-v] [--quiet|-q] [--help|-h]"
+   echo >&2 "Example: $0 Image.jpeg Cloth.png --depth 5"
+   exit "${exitCode}"
+}
+
+GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
+# shellcheck disable=SC2068
+options="$(${GETOPT} -o d:vqh --long depth:,verbose,quiet,help -a -- "$@")"
+eval set -- "${options}"
+
+DEPTH=5
+VERBOSE=0
+while [ $# -gt 0 ] ; do
+   case "$1" in
+      -d | --depth)
+         DEPTH="$2"
+         shift 2
+         ;;
+      -v | --verbose)
+         VERBOSE=1
+         shift
+         ;;
+      -q | --quiet)
+         VERBOSE=0
+         shift
+         ;;
+      -h | --help)
+         usage 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         usage 1
+         ;;
+  esac
+done
+
+if [ $# -ne 2 ] ; then
+   usage 1
+fi
+INPUT_FILENAME="$1"
+OUTPUT_FILENAME="$2"
+
+if [ ! -f "${INPUT_FILENAME}" ] ; then
+   echo >&2 "ERROR: Input file ${INPUT_FILENAME} does not exist!"
    exit 1
 fi
-INPUTFILENAME="$1"
-OUTPUTFILENAME="$2"
-DEPTH=5
-if [ $# -gt 2 ] ; then
-   DEPTH="$3"
+if [[ ! "${DEPTH}" =~ ^([0-9]+)$ ]] ; then
+   echo >&2 "ERROR: Invalid depth ${DEPTH}!"
+   exit 1
 fi
+
+
+# ====== Obtain GIMP call options ===========================================
+if ! whereis gimp-console >/dev/null ; then
+   echo >&2 "ERROR: Gimp is not available!"
+   exit 1
+fi
+GIMP_VERSION="$(LANG=C gimp-console --version | sed -e 's/GNU Image Manipulation Program version //')"
+if [[ "${GIMP_VERSION}" =~ ^[012] ]] ; then
+   # Gimp 2.x:
+   GIMP_OPTIONS="--new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
+else
+   # Gimp 3.x:
+   GIMP_OPTIONS="--quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
+fi
+
+# This script does not use fonts, or gradients/palettes/brushes:
+GIMP_OPTIONS="${GIMP_OPTIONS} --no-fonts --no-data"
 
 
 # ====== Call GIMP ==========================================================
-rm -f "$OUTPUTFILENAME"
+rm -f "${OUTPUT_FILENAME}"
+# shellcheck disable=SC2086
 ( cat <<EOF
 (let*
-   ((inputFileName    "$INPUTFILENAME")
-    (outputFileName   "$OUTPUTFILENAME")
-    (depth            $DEPTH)
-    (image (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
-    (drawable (car (gimp-image-get-active-layer image)))
+   ; ------ Initialise and load image ---------------------------------------
+   ((inputFileName    "${INPUT_FILENAME}")
+    (outputFileName   "${OUTPUT_FILENAME}")
+    (depth            ${DEPTH})
+    (image            (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
+    (imageType        (if (not (defined? 'gimp-image-get-active-layer))
+                         ; New Gimp 3.0 API:
+                         (car (gimp-image-get-base-type image))
+                         ; Old Gimp 2.x API:
+                         (car (gimp-image-base-type image)))
+                      )
+    (layer            (if (not (defined? 'gimp-image-get-active-layer))
+                         ; New Gimp 3.0 API:
+                         (car (list (vector-ref (car (gimp-image-get-selected-layers image)) 0)))
+                         ; Old Gimp 2.x API:
+                         (car (gimp-image-get-active-layer image)))
+                      )
    )
-   ; ------------------------------------------------------------------------
-   (script-fu-clothify image drawable 1 1 135.0 45.0 depth)
-   ; ------------------------------------------------------------------------
-   (file-png-save2 RUN-NONINTERACTIVE image drawable outputFileName outputFileName TRUE 9 TRUE TRUE FALSE TRUE TRUE FALSE TRUE)
+
+   ; ------ Apply filter ----------------------------------------------------
+   ; First, make sure that the image is RGB, not indexed color mode!
+   (if (not (= RGB imageType))
+      (gimp-image-convert-rgb image))
+
+   (cond( (not(defined? 'plug-in-bump-map))
+      ; New Gimp 3.0 API:
+      (script-fu-clothify image (vector layer) 1 1 135.0 45.0 depth)
+   )
+   (else
+      ; Old Gimp 2.x API:
+      (script-fu-clothify image layer 1 1 135.0 45.0 depth)
+   ))
+
+   ; ------ Save result -----------------------------------------------------
+   (if (defined? 'gimp-drawable-merge-new-filter)
+      (begin  ; New Gimp >= 3.0 API:
+         ; FIXME: This does not work when running in Gimp 2.x!
+         ; (file-png-export
+         ;    #:run-mode         RUN-NONINTERACTIVE
+         ;    #:image            image
+         ;    #:file             outputFileName
+         ;    #:options          -1
+         ;    #:interlaced       TRUE
+         ;    #:compression      6
+         ;    #:bkgd             TRUE
+         ;    #:offs             FALSE
+         ;    #:phys             TRUE
+         ;    #:time             TRUE
+         ;    #:save-transparent FALSE
+         ;    #:optimize-palette TRUE
+         ; )
+         (file-png-export RUN-NONINTERACTIVE image
+            outputFileName -1
+            TRUE 6 TRUE FALSE TRUE TRUE FALSE TRUE)
+      )
+      (begin  ; Old Gimp < 3.0 API:
+         (file-png-save2 RUN-NONINTERACTIVE image
+            (car (gimp-image-get-active-layer image))
+            outputFileName outputFileName
+            TRUE 6 TRUE TRUE FALSE TRUE TRUE FALSE TRUE)
+      )
+   )
+
+   ; ------ Clean up --------------------------------------------------------
+   (gimp-image-delete image)
 )
 (gimp-quit TRUE)
 EOF
-) | env LANG=C HOME=/tmp gimp --new-instance --no-interface --no-splash --batch - 2>&1 | \
-       ( grep -vE "^ts>|(#t)|^Copyright|^Welcome|GLib-GObject-WARNING|GEGL-gegl-operation.c-WARNING|GEGL-CRITICAL|missing babl fast path|Missing fast-path babl|accelerates GEGL|first occurance of formats|programmatically by bab|GeglBuffers leaked|Failed to parse tag cache|^$" || true )
+) | env LANG=C HOME=/tmp gimp-console ${GIMP_OPTIONS} 2>&1 | \
+(
+   if [ ${VERBOSE} -ne 0 ] ; then
+      cat
+   else
+      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
+   fi
+)
 
-if [ ! -e "$OUTPUTFILENAME" ] ; then
-   echo >&2 "ERROR: $OUTPUTFILENAME has not been produced. Something went wrong!"
+
+# ====== Check result =======================================================
+if [ ! -e "${OUTPUT_FILENAME}" ] ; then
+   echo >&2 "ERROR: ${OUTPUT_FILENAME} has not been produced. Something went wrong!"
    exit 1
 fi
diff --git a/files/backgrounds/gimp-scripts/Make-Mosaic b/files/backgrounds/gimp-scripts/Make-Mosaic
--- a/files/backgrounds/gimp-scripts/Make-Mosaic
+++ b/files/backgrounds/gimp-scripts/Make-Mosaic
@@ -19,84 +19,264 @@
 # Contact: thomas.dreibholz@gmail.com
 
 # Bash options:
-set -e
+set -eu
 
 
 # Example:
-# Make-Mosaic Image.jpeg Mosaic 24 4 4 hexagons rough
-# Make-Mosaic Image.jpeg Mosaic 32 4 2 octagons smooth
+# Make-Mosaic Image1.jpeg Mosaic1.png 24 4 4 --type hexagons --surface rough
+# Make-Mosaic Image1.jpeg Mosaic2.png 32 4 2 --type octagons --surface smooth
 
 
 # ====== Handle arguments ===================================================
-if [ $# -lt 5 ] ; then
-   echo >&2 "Usage: $0 input_filename output_filename tile_size tile_height tile_spacing [squares|hexagons|octagons|triangles [smooth|rough]]"
+usage () {
+   local exitCode="$1"
+   echo >&2 "Usage: $0 input_filename output_filename tile_size tile_height tile_spacing [--type|-t squares|hexagons|octagons|triangles] [--surface|-s smooth|rough] [--neatness|-n neatness] [--lightdirection|-l direction] [-c|--colorvariation variation] [--verbose|-v] [--quiet|-q] [--help|-h]"
+   echo >&2 "Example: $0 Image.jpeg Mosaic.png 24 4 4 --type hexagons --surface rough"
+   exit "${exitCode}"
+}
+
+GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
+# shellcheck disable=SC2068
+options="$(${GETOPT} -o t:s:n:l:c:vqh --long type:,surface:,neatness:,lightdirection:,colorvariation:,verbose,quiet,help -a -- "$@")"
+eval set -- "${options}"
+
+TILE_NEATNESS=0.65
+TILE_TYPESTRING="hexagons"
+TILE_TYPE="6"
+TILE_SURFACE=0
+LIGHT_DIRECTION=135
+COLOR_VARIATION=0.2
+VERBOSE=0
+while [ $# -gt 0 ] ; do
+   case "$1" in
+      -t | --type)
+         TILE_TYPESTRING="$2"
+         shift 2
+         ;;
+      -s | --surface)
+         if [ "$2" == "smooth" ] ; then
+            TILE_SURFACE=0
+         elif [ "$2" == "rough" ] ; then
+            TILE_SURFACE=1
+         else
+            echo >&2 "Invalid tile surface: $2"
+            exit 1
+         fi
+         shift 2
+         ;;
+      -n | --neatness)
+         TILE_NEATNESS="$2"
+         shift 2
+         ;;
+      -l | --lightdirection)
+         LIGHT_DIRECTION="$2"
+         shift 2
+         ;;
+      -c | --colorvariation)
+         COLOR_VARIATION="$2"
+         shift 2
+         ;;
+      -v | --verbose)
+         VERBOSE=1
+         shift
+         ;;
+      -q | --quiet)
+         VERBOSE=0
+         shift
+         ;;
+      -h | --help)
+         usage 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         usage 1
+         ;;
+  esac
+done
+
+if [ $# -ne 5 ] ; then
+   usage 1
+fi
+INPUT_FILENAME="$1"
+OUTPUT_FILENAME="$2"
+TILE_SIZE=$3
+TILE_HEIGHT=$4
+TILE_SPACING=$5
+
+if [ ! -f "${INPUT_FILENAME}" ] ; then
+   echo >&2 "ERROR: Input file ${INPUT_FILENAME} does not exist!"
    exit 1
 fi
-INPUTFILENAME="$1"
-OUTPUTFILENAME="$2"
-TILESIZE=$3
-TILEHEIGHT=$4
-TILESPACING=$5
-TILETYPE="1"
-TILESURFACE=0
-if [ $# -gt 5 ] ; then
-   if [ "$6" = "squares" ] ; then
-      TILETYPE=0
-   elif [ "$6" = "hexagons" ] ; then
-      TILETYPE=1
-   elif [ "$6" = "octagons" ] ; then
-      TILETYPE=2
-   elif [ "$6" = "triangles]" ] ; then
-      TILETYPE=3
-   else
-      echo >&2 "Invalid tile type: $6"
-      exit 1
-   fi
+if [[ ! "${TILE_SIZE}" =~ ^[0-9]+$ ]] ; then
+   echo >&2 "ERROR: Invalid tile size!"
+   exit 1
 fi
-if [ $# -gt 6 ] ; then
-   if [ "$7" = "smooth" ] ; then
-      TILESURFACE=0
-   elif [ "$7" = "rough" ] ; then
-      TILESURFACE=1
-   else
-      echo >&2 "Invalid tile surface: $7"
-      exit 1
-   fi
+if [[ ! "${TILE_HEIGHT}" =~ ^[0-9]+$ ]] ; then
+   echo >&2 "ERROR: Invalid tile height!"
+   exit 1
 fi
+if [[ ! "${TILE_SPACING}" =~ ^[0-9]+$ ]] ; then
+   echo >&2 "ERROR: Invalid tile spacing!"
+   exit 1
+fi
+if [ "${TILE_TYPESTRING}" = "squares" ] ; then
+   TILE_TYPE=0
+elif [ "${TILE_TYPESTRING}" = "hexagons" ] ; then
+   TILE_TYPE=1
+elif [ "${TILE_TYPESTRING}" = "octagons" ] ; then
+   TILE_TYPE=2
+elif [ "${TILE_TYPESTRING}" = "triangles" ] ; then
+   TILE_TYPE=3
+else
+   echo >&2 "Invalid tile type ${TILE_TYPESTRING}!"
+   exit 1
+fi
+if [[ ! "${TILE_NEATNESS}" =~ ^([0-9]+|[0-9]+\.[0-9]*)$ ]] ; then
+   echo >&2 "ERROR: Invalid tile neatness ${TILE_NEATNESS}!"
+   exit 1
+fi
+if [[ ! "${COLOR_VARIATION}" =~ ^([0-9]+|[0-9]+\.[0-9]*)$ ]] ; then
+   echo >&2 "ERROR: Invalid color variation ${COLOR_VARIATION}!"
+   exit 1
+fi
+if [[ ! "${LIGHT_DIRECTION}" =~ ^([0-9]+)$ ]] ; then
+   echo >&2 "ERROR: Invalid light direction ${LIGHT_DIRECTION}!"
+   exit 1
+fi
+
+
+# ====== Obtain GIMP call options ===========================================
+if ! whereis gimp-console >/dev/null ; then
+   echo >&2 "ERROR: Gimp is not available!"
+   exit 1
+fi
+GIMP_VERSION="$(LANG=C gimp-console --version | sed -e 's/GNU Image Manipulation Program version //')"
+if [[ "${GIMP_VERSION}" =~ ^[012] ]] ; then
+   # Gimp 2.x:
+   GIMP_OPTIONS="--new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
+else
+   # Gimp 3.x:
+   GIMP_OPTIONS="--quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
+fi
+
+# This script does not use fonts, or gradients/palettes/brushes:
+GIMP_OPTIONS="${GIMP_OPTIONS} --no-fonts --no-data"
+
 
 # ====== Call GIMP ==========================================================
-rm -f "$OUTPUTFILENAME"
+rm -f "${OUTPUT_FILENAME}"
+# shellcheck disable=SC2086
 ( cat <<EOF
 (let*
-   ((inputFileName    "$INPUTFILENAME")
-    (outputFileName   "$OUTPUTFILENAME")
-    (tileType         $TILETYPE)
-    (tileSize         $TILESIZE)
-    (tileHeight       $TILEHEIGHT)
-    (tileSpacing      $TILESPACING)
-    (tileSurface      $TILESURFACE)
-    (image (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
-    (drawable (car (gimp-image-get-active-layer image)))
+   ; ------ Initialise and load image ---------------------------------------
+   ((inputFileName    "${INPUT_FILENAME}")
+    (outputFileName   "${OUTPUT_FILENAME}")
+    (tileType         ${TILE_TYPE})
+    (tileTypeString   "${TILE_TYPESTRING}")
+    (tileSize         ${TILE_SIZE})
+    (tileHeight       ${TILE_HEIGHT})
+    (tileSpacing      ${TILE_SPACING})
+    (tileNeatness     ${TILE_NEATNESS})
+    (tileSurface      ${TILE_SURFACE})
+    (lightDirection   ${LIGHT_DIRECTION})
+    (colorVariation   ${COLOR_VARIATION})
+    (image            (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
+    (imageType        (if (not (defined? 'gimp-image-get-active-layer))
+                         ; New Gimp 3.0 API:
+                         (car (gimp-image-get-base-type image))
+                         ; Old Gimp 2.x API:
+                         (car (gimp-image-base-type image)))
+                      )
+    (layer            (if (not (defined? 'gimp-image-get-active-layer))
+                         ; New Gimp 3.0 API:
+                         (car (list (vector-ref (car (gimp-image-get-selected-layers image)) 0)))
+                         ; Old Gimp 2.x API:
+                         (car (gimp-image-get-active-layer image)))
+                      )
    )
-   ; ------------------------------------------------------------------------
-   ; First, make sure that the image is RGB, not indexed color mode!
-   (if (not (= RGB (car (gimp-image-base-type image))))
-             (gimp-image-convert-rgb image))
 
-   (plug-in-mosaic RUN-NONINTERACTIVE image drawable
-       tileSize tileHeight tileSpacing
-       0.65 TRUE 135.0 0.2 TRUE TRUE
-       tileType tileSurface FALSE)
-   ; ------------------------------------------------------------------------
-   (file-png-save2 RUN-NONINTERACTIVE image drawable outputFileName outputFileName TRUE 9 TRUE TRUE FALSE TRUE TRUE FALSE TRUE)
+   ; ------ Apply filter ----------------------------------------------------
+   ; First, make sure that the image is RGB, not indexed color mode!
+   (if (not (= RGB imageType))
+      (gimp-image-convert-rgb image))
+
+   ; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+   ; GEGL Mosaic options: https://gegl.org/operations/gegl-mosaic.html
+   ; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+
+   (cond( (not(defined? 'plug-in-mosaic))
+      ; New Gimp 3.0 API:
+      (gimp-drawable-merge-new-filter layer "gegl:mosaic" 0 LAYER-MODE-REPLACE 1.0
+          "tile-size"       tileSize
+          "tile-height"     tileHeight
+          "tile-spacing"    tileSpacing
+          "tile-neatness"   tileNeatness
+          "antialiasing"    TRUE
+          "light-dir"       lightDirection
+          "color-variation" colorVariation
+          "tile-type"       tileTypeString
+          "tile-surface"    tileSurface
+          "seed"            0
+      )
+   )
+   (else
+      ; Old Gimp 2.x API:
+      (plug-in-mosaic RUN-NONINTERACTIVE image layer
+         tileSize tileHeight tileSpacing
+         tileNeatness TRUE lightDirection colorVariation TRUE TRUE
+         tileType tileSurface FALSE
+   )))
+
+   ; ------ Save result -----------------------------------------------------
+   (if (defined? 'gimp-drawable-merge-new-filter)
+      (begin  ; New Gimp >= 3.0 API:
+         ; FIXME: This does not work when running in Gimp 2.x!
+         ; (file-png-export
+         ;    #:run-mode         RUN-NONINTERACTIVE
+         ;    #:image            image
+         ;    #:file             outputFileName
+         ;    #:options          -1
+         ;    #:interlaced       TRUE
+         ;    #:compression      6
+         ;    #:bkgd             TRUE
+         ;    #:offs             FALSE
+         ;    #:phys             TRUE
+         ;    #:time             TRUE
+         ;    #:save-transparent FALSE
+         ;    #:optimize-palette TRUE
+         ; )
+         (file-png-export RUN-NONINTERACTIVE image
+            outputFileName -1
+            TRUE 6 TRUE FALSE TRUE TRUE FALSE TRUE)
+      )
+      (begin  ; Old Gimp < 3.0 API:
+         (file-png-save2 RUN-NONINTERACTIVE image
+            (car (gimp-image-get-active-layer image))
+            outputFileName outputFileName
+            TRUE 6 TRUE TRUE FALSE TRUE TRUE FALSE TRUE)
+      )
+   )
+
+   ; ------ Clean up --------------------------------------------------------
+   (gimp-image-delete image)
 )
 (gimp-quit TRUE)
 EOF
-) | \
-env LANG=C HOME=/tmp gimp-console --batch-interpreter plug-in-script-fu-eval --new-instance --no-interface --no-splash --batch - 2>&1 | \
-( grep -vE "^ts>|(#t)|^Copyright|^Welcome|GLib-GObject-WARNING|GEGL-gegl-operation.c-WARNING|GEGL-CRITICAL|missing babl fast path|Missing fast-path babl|accelerates GEGL|first occurance of formats|programmatically by bab|GeglBuffers leaked|Failed to parse tag cache|Ignoring XMP|Exif.Canon.CRWParam|^$" || true )
+) | env LANG=C HOME=/tmp gimp-console ${GIMP_OPTIONS} 2>&1 | \
+(
+   if [ ${VERBOSE} -ne 0 ] ; then
+      cat
+   else
+      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
+   fi
+)
 
-if [ ! -e "$OUTPUTFILENAME" ] ; then
-   echo >&2 "ERROR: $OUTPUTFILENAME has not been produced. Something went wrong!"
+
+# ====== Check result =======================================================
+if [ ! -e "${OUTPUT_FILENAME}" ] ; then
+   echo >&2 "ERROR: ${OUTPUT_FILENAME} has not been produced. Something went wrong!"
    exit 1
 fi
diff --git a/files/backgrounds/gimp-scripts/Make-OldPhoto b/files/backgrounds/gimp-scripts/Make-OldPhoto
--- a/files/backgrounds/gimp-scripts/Make-OldPhoto
+++ b/files/backgrounds/gimp-scripts/Make-OldPhoto
@@ -19,53 +19,169 @@
 # Contact: thomas.dreibholz@gmail.com
 
 # Bash options:
-set -e
+set -eu
 
 
-# Example:
-# Make-OldPhoto Image.jpeg OldPhoto.png 20
+# Examples:
+# Make-OldPhoto Image1.jpeg OldPhoto1.png
+# Make-OldPhoto Image1.jpeg OldPhoto2.png --bordersize 20
 
 
 # ====== Handle arguments ===================================================
-if [ $# -lt 2 ] ; then
-   echo >&2 "Usage: $0 input_filename output_filename [border_size]"
+usage () {
+   local exitCode="$1"
+   echo >&2 "Usage: $0 input_filename output_filename [--bordersize|-b size] [--verbose|-v] [--quiet|-q] [--help|-h]"
+   echo >&2 "Example: $0 Image.jpeg OldPhoto.png --bordersize 20"
+   exit "${exitCode}"
+}
+
+GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
+# shellcheck disable=SC2068
+options="$(${GETOPT} -o b:vqh --long bordersize:,verbose,quiet,help -a -- "$@")"
+eval set -- "${options}"
+
+BORDER_SIZE=10
+VERBOSE=0
+while [ $# -gt 0 ] ; do
+   case "$1" in
+      -b | --bordersize)
+         BORDER_SIZE="$2"
+         shift 2
+         ;;
+      -v | --verbose)
+         VERBOSE=1
+         shift
+         ;;
+      -q | --quiet)
+         VERBOSE=0
+         shift
+         ;;
+      -h | --help)
+         usage 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         usage 1
+         ;;
+  esac
+done
+
+if [ $# -ne 2 ] ; then
+   usage 1
+fi
+INPUT_FILENAME="$1"
+OUTPUT_FILENAME="$2"
+
+if [ ! -f "${INPUT_FILENAME}" ] ; then
+   echo >&2 "ERROR: Input file ${INPUT_FILENAME} does not exist!"
    exit 1
 fi
-INPUTFILENAME="$1"
-OUTPUTFILENAME="$2"
-BORDERSIZE=20
-if [ $# -gt 2 ] ; then
-   BORDERSIZE="$3"
+if [[ ! "${BORDER_SIZE}" =~ ^([0-9]+)$ ]] ; then
+   echo >&2 "ERROR: Invalid border size ${BORDER_SIZE}!"
+   exit 1
 fi
+
+
+# ====== Obtain GIMP call options ===========================================
+if ! whereis gimp-console >/dev/null ; then
+   echo >&2 "ERROR: Gimp is not available!"
+   exit 1
+fi
+GIMP_VERSION="$(LANG=C gimp-console --version | sed -e 's/GNU Image Manipulation Program version //')"
+if [[ "${GIMP_VERSION}" =~ ^[012] ]] ; then
+   # Gimp 2.x:
+   GIMP_OPTIONS="--new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
+else
+   # Gimp 3.x:
+   GIMP_OPTIONS="--quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
+fi
+
+# This script does not use fonts, or gradients/palettes/brushes:
+GIMP_OPTIONS="${GIMP_OPTIONS} --no-fonts --no-data"
 
 
 # ====== Call GIMP ==========================================================
-rm -f "$OUTPUTFILENAME"
+rm -f "${OUTPUT_FILENAME}"
+# shellcheck disable=SC2086
 ( cat <<EOF
 (let*
-   ((inputFileName    "$INPUTFILENAME")
-    (outputFileName   "$OUTPUTFILENAME")
-    (borderSize       $BORDERSIZE)
-    (image (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
-    (drawable (car (gimp-image-get-active-layer image)))
+   ; ------ Initialise and load image ---------------------------------------
+   ((inputFileName    "${INPUT_FILENAME}")
+    (outputFileName   "${OUTPUT_FILENAME}")
+    (borderSize       ${BORDER_SIZE})
+    (image            (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
+    (imageType        (if (not (defined? 'gimp-image-get-active-layer))
+                         ; New Gimp 3.0 API:
+                         (car (gimp-image-get-base-type image))
+                         ; Old Gimp 2.x API:
+                         (car (gimp-image-base-type image)))
+                      )
+    (layer            (if (not (defined? 'gimp-image-get-active-layer))
+                         ; New Gimp 3.0 API:
+                         (car (list (vector-ref (car (gimp-image-get-selected-layers image)) 0)))
+                         ; Old Gimp 2.x API:
+                         (car (gimp-image-get-active-layer image)))
+                      )
    )
-   ; ------------------------------------------------------------------------
-   ; First, make sure that the image is RGB, not indexed color mode!
-   (if (not (= RGB (car (gimp-image-base-type image))))
-             (gimp-image-convert-rgb image))
 
-   (script-fu-old-photo image drawable
+   ; ------ Apply filter ----------------------------------------------------
+   ; First, make sure that the image is RGB, not indexed color mode!
+   (if (not (= RGB imageType))
+      (gimp-image-convert-rgb image))
+
+   (script-fu-old-photo image layer
                         TRUE borderSize TRUE FALSE FALSE)
-   ; ------------------------------------------------------------------------
-   (file-png-save2 RUN-NONINTERACTIVE image (car (gimp-image-get-active-layer image))
-                   outputFileName outputFileName TRUE 9 TRUE TRUE FALSE TRUE TRUE FALSE TRUE)
+
+   ; ------ Save result -----------------------------------------------------
+   (if (defined? 'gimp-drawable-merge-new-filter)
+      (begin  ; New Gimp >= 3.0 API:
+         ; FIXME: This does not work when running in Gimp 2.x!
+         ; (file-png-export
+         ;    #:run-mode         RUN-NONINTERACTIVE
+         ;    #:image            image
+         ;    #:file             outputFileName
+         ;    #:options          -1
+         ;    #:interlaced       TRUE
+         ;    #:compression      6
+         ;    #:bkgd             TRUE
+         ;    #:offs             FALSE
+         ;    #:phys             TRUE
+         ;    #:time             TRUE
+         ;    #:save-transparent FALSE
+         ;    #:optimize-palette TRUE
+         ; )
+         (file-png-export RUN-NONINTERACTIVE image
+            outputFileName -1
+            TRUE 6 TRUE FALSE TRUE TRUE FALSE TRUE)
+      )
+      (begin  ; Old Gimp < 3.0 API:
+         (file-png-save2 RUN-NONINTERACTIVE image
+            (car (gimp-image-get-active-layer image))
+            outputFileName outputFileName
+            TRUE 6 TRUE TRUE FALSE TRUE TRUE FALSE TRUE)
+      )
+   )
+
+   ; ------ Clean up --------------------------------------------------------
+   (gimp-image-delete image)
 )
 (gimp-quit TRUE)
 EOF
-) | env LANG=C HOME=/tmp gimp --new-instance --no-interface --no-splash --batch - 2>&1 | \
-       ( grep -vE "^ts>|(#t)|^Copyright|^Welcome|GLib-GObject-WARNING|GEGL-gegl-operation.c-WARNING|GEGL-CRITICAL|missing babl fast path|Missing fast-path babl|accelerates GEGL|first occurance of formats|programmatically by bab|GeglBuffers leaked|Failed to parse tag cache|^$" || true )
+) | env LANG=C HOME=/tmp gimp-console ${GIMP_OPTIONS} 2>&1 | \
+(
+   if [ ${VERBOSE} -ne 0 ] ; then
+      cat
+   else
+      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
+   fi
+)
 
-if [ ! -e "$OUTPUTFILENAME" ] ; then
-   echo >&2 "ERROR: $OUTPUTFILENAME has not been produced. Something went wrong!"
+
+# ====== Check result =======================================================
+if [ ! -e "${OUTPUT_FILENAME}" ] ; then
+   echo >&2 "ERROR: ${OUTPUT_FILENAME} has not been produced. Something went wrong!"
    exit 1
 fi
diff --git a/files/backgrounds/gimp-scripts/Test-Gimp b/files/backgrounds/gimp-scripts/Test-Gimp
--- a/files/backgrounds/gimp-scripts/Test-Gimp
+++ b/files/backgrounds/gimp-scripts/Test-Gimp
@@ -19,21 +19,98 @@
 # Contact: thomas.dreibholz@gmail.com
 
 # Bash options:
-set -e
+set -eu
 
 
-# ====== Make sure that GIMP directory exists ===============================
-if [ "${GIMP2_DIRECTORY}" != "" ] ; then
-   echo "Creating GIMP directory ${GIMP2_DIRECTORY}"
-   for subdir in brushes dynamics patterns gradients palettes ; do
-      mkdir -p "${GIMP2_DIRECTORY}/${subdir}"
-   done
+# ====== Handle arguments ===================================================
+usage () {
+   local exitCode="$1"
+   echo >&2 "Usage: $0 [--verbose|-v] [--quiet|-q] [--help|-h]"
+   echo >&2 "Example: $0 --verbose"
+   exit "${exitCode}"
+}
+
+GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
+# shellcheck disable=SC2068
+options="$(${GETOPT} -o vqh --long verbose,quiet,help -a -- "$@")"
+eval set -- "${options}"
+
+VERBOSE=0
+while [ $# -gt 0 ] ; do
+   case "$1" in
+      -v | --verbose)
+         VERBOSE=1
+         shift
+         ;;
+      -q | --quiet)
+         VERBOSE=0
+         shift
+         ;;
+      -h | --help)
+         usage 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         usage 1
+         ;;
+  esac
+done
+
+if [ $# -ne 0 ] ; then
+   usage 1
+fi
+
+if [ ! -v GIMP3_DIRECTORY ] ; then
+   echo >&2 "ERROR: Environment variable GIMP3_DIRECTORY is not defined!"
+   exit 1
 fi
 
 
+# ====== Make sure that GIMP directory exists ===============================
+if [ "${GIMP3_DIRECTORY}" != "" ] ; then
+   echo "Creating GIMP directory ${GIMP3_DIRECTORY} ..."
+   for subdir in brushes dynamics patterns gradients palettes ; do
+      mkdir -p "${GIMP3_DIRECTORY}/${subdir}"
+   done
+
+   # FIXME!
+   # Gimp 3.0 wastes a lot of CPU, for whatever reason. Just
+   # using 1 core seems to provide the best performance:
+   echo "(num-processors 1)" >>"${GIMP3_DIRECTORY}/gimprc"
+fi
+
+
+# ====== Obtain GIMP call options ===========================================
+if ! whereis gimp-console >/dev/null ; then
+   echo >&2 "ERROR: Gimp is not available!"
+   exit 1
+fi
+GIMP_VERSION="$(LANG=C gimp-console --version | sed -e 's/GNU Image Manipulation Program version //')"
+if [[ "${GIMP_VERSION}" =~ ^[012] ]] ; then
+   # Gimp 2.x:
+   GIMP_OPTIONS="--new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
+else
+   # Gimp 3.x:
+   GIMP_OPTIONS="--quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
+fi
+
+# This script does not use fonts, or gradients/palettes/brushes:
+GIMP_OPTIONS="${GIMP_OPTIONS} --no-fonts --no-data"
+
+
 # ====== Try to start GIMP ==================================================
+# shellcheck disable=SC2086
 ( cat <<EOF
 (gimp-quit TRUE)
 EOF
-) | env LANG=C HOME=/tmp gimp --new-instance --no-interface --no-splash --batch - 2>&1 | \
-       ( grep -vE "^ts>|(#t)|^Copyright|^Welcome|GLib-GObject-WARNING|GEGL-gegl-operation.c-WARNING|GEGL-CRITICAL|missing babl fast path|Missing fast-path babl|accelerates GEGL|first occurance of formats|programmatically by bab|GeglBuffers leaked|Failed to parse tag cache|^$" || true )
+) | env LANG=C HOME=/tmp gimp-console ${GIMP_OPTIONS} 2>&1 | \
+(
+   if [ ${VERBOSE} -ne 0 ] ; then
+      cat
+   else
+      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
+   fi
+)
