Solaris improvements.

diff --git a/scripts/10-basic b/scripts/10-basic
--- a/scripts/10-basic
+++ b/scripts/10-basic
@@ -635,6 +635,7 @@ elif [ "${ID}" == "sunos" ] ; then
       fail2ban
       gawk
       gptfdisk
+      gtk3   # FIXME: Something seems to require GTK3, otherwise svc:/application/desktop-cache/input-method-cache:default fails.
 #      hipercontracer
       htop
       joe
@@ -673,7 +674,7 @@ elif [ "${ID}" == "sunos" ] ; then
       ( cd figlet && sed -e 's%^prefix\t=.*$%prefix\t= /usr%' -i Makefile && make CFLAGS="-Wall -DTLF_FONTS -include alloca.h" && make install )
    fi
    if ! command -v print-utf8 >/dev/null ; then
-      pkg install pkg://openindiana.org/developer/build/cmake gcc-14 pkgconf  gnu-gettext pkg://openindiana.org/developer/g++/icu mbuffer pwgen || [ $? -eq 4 ]
+      pkg install pkg://openindiana.org/developer/build/cmake gcc-14 gnu-getopt pkgconf  gnu-gettext pkg://openindiana.org/developer/g++/icu mbuffer pwgen || [ $? -eq 4 ]
       clone-or-update system-tools https://dreibh@github.com/dreibh/system-tools
       ( cd /root/src/system-tools && ./autogen.sh -- -DWITH_CONFIGURE_GRUB=OFF -DWITH_GIMP_SCRIPTS=OFF -DWITH_GIMP_SCRIPTS_EXAMPLES=OFF && make install )
    fi
@@ -683,12 +684,12 @@ elif [ "${ID}" == "sunos" ] ; then
       ( cd /root/src/subnetcalc && ./autogen.sh -- -DWITH_GEOIP=OFF && make install )
    fi
    if ! command -v netperfmeter >/dev/null ; then
-      pkg install pkg://openindiana.org/developer/build/cmake gcc-14 pkgconf  compress/bzip2 || [ $? -eq 4 ]
+      pkg install pkg://openindiana.org/developer/build/cmake gcc-14 gnu-getopt pkgconf  compress/bzip2 || [ $? -eq 4 ]
       clone-or-update netperfmeter https://dreibh@github.com/dreibh/netperfmeter
       ( cd /root/src/netperfmeter && ./autogen.sh -- -DWITH_ICONS=OFF && make install )
    fi
    if ! command -v hipercontracer >/dev/null ; then
-      pkg install pkg://openindiana.org/developer/build/cmake gcc-14 pkgconf  library/boost compress/bzip2 compress/xz compress/zstd || [ $? -eq 4 ]
+      pkg install pkg://openindiana.org/developer/build/cmake gcc-14 gnu-getopt pkgconf  library/boost compress/bzip2 compress/xz compress/zstd || [ $? -eq 4 ]
       clone-or-update hipercontracer https://dreibh@github.com/dreibh/hipercontracer
       ( cd /root/src/hipercontracer && ./autogen.sh -- -DWITH_ICONS=OFF -DWITH_IMPORTER=OFF -DWITH_QUERY=OFF -DWITH_LIBHPCTDB=OFF -DWITH_LIBUNIVERSALIMPORTER=OFF && make install )
    fi
@@ -698,7 +699,7 @@ elif [ "${ID}" == "sunos" ] ; then
       ( cd /root/src/tsctp && ./autogen.sh && make install )
    fi
 #   if ! command -v rspterminal >/dev/null ; then
-#      pkg install pkg://openindiana.org/developer/build/cmake gcc-14 pkgconf || [ $? -eq 4 ]
+#      pkg install pkg://openindiana.org/developer/build/cmake gcc-14 gnu-getopt pkgconf || [ $? -eq 4 ]
 #      clone-or-update rsplib https://dreibh@github.com/dreibh/rsplib
 #      ( cd /root/src/rsplib && ./autogen.sh -- -DENABLE_ICONS=OFF -DENABLE_QT=OFF && make install )
 #   fi
