Improved configurations.

diff --git a/scripts/10-minimal b/scripts/10-minimal
--- a/scripts/10-minimal
+++ b/scripts/10-minimal
@@ -28,6 +28,12 @@ set -e
 # installation:
 # - Ping (network connectivity check)
 # - cURL (download tool)
+#
+# Further properties:
+# - ECN enabled
+# - SCTP enabled
+# - SSH server enabled
+# - UTF-8 character encoding
 # ###########################################################################
 
 
@@ -36,9 +42,10 @@ set -e
 # ------ Ubuntu -------------------------------------------------------------
 if [ -e /usr/bin/apt-get ] ; then
 
+   # Make 3 APT package download retries, in case of network problems:
    echo 'Acquire::Retries "3";' >/etc/apt/apt.conf.d/80retries
 
-   # Just ensure the package database is up-to-date
+   # Just ensure the package database is up-to-date:
    /usr/bin/apt-get update
 
 # ------ Fedora -------------------------------------------------------------
@@ -69,6 +76,6 @@ for command in ping curl ; do
    fi
 done
 if [ ${errors} -gt 0 ] ; then
-   echo "ERROR: ${errors} packages are missing!"
+   echo >&2 "ERROR: ${errors} packages are missing!"
    exit 1
 fi
diff --git a/scripts/11-basic b/scripts/11-basic
--- a/scripts/11-basic
+++ b/scripts/11-basic
@@ -198,6 +198,6 @@ for command in base64 bwm-ng bzip2 curl locate gdisk gpg hipercontracer htop ifc
    fi
 done
 if [ ${errors} -gt 0 ] ; then
-   echo "ERROR: ${errors} packages are missing!"
+   echo >&2 "ERROR: ${errors} packages are missing!"
    exit 1
 fi
diff --git a/scripts/30-development b/scripts/30-development
--- a/scripts/30-development
+++ b/scripts/30-development
@@ -107,7 +107,7 @@ fi
 # ====== Verify command availability ========================================
 echo "Verifying command availability:"
 errors=0
-for command in autoconf automake cmake g++ gcc gm libtool make valgrind ; do
+for command in autoconf automake cmake g++ gcc gdb gm libtool make valgrind ; do
    echo -n "${command}: "
    if which ${command} >/dev/null ; then
       echo "OK"
@@ -117,6 +117,6 @@ for command in autoconf automake cmake g++ gcc gm libtool make valgrind ; do
    fi
 done
 if [ ${errors} -gt 0 ] ; then
-   echo "ERROR: ${errors} packages are missing!"
+   echo >&2 "ERROR: ${errors} packages are missing!"
    exit 1
 fi
