Further NetBSD improvements.

diff --git a/scripts/30-development b/scripts/30-development
--- a/scripts/30-development
+++ b/scripts/30-development
@@ -504,13 +504,22 @@ elif [ "${ID}" == "netbsd" ] ; then
    pkgin -y install "${packages[@]}"
 
    # Fetch and check out the NetBSD Ports Collection:
-   if [ -d /usr/pkgsrc/.git ] ; then
+   if [ -d "/usr/pkgsrc/.git" ] ; then
       cd /usr/pkgsrc
       git fetch --all
       git checkout trunk
       git pull
    else
       echo >&2 "ERROR: /usr/pkgsrc is not initialised as a Git repository!"
+      exit 1
+   fi
+   if [ -d "/usr/pkgsrc/wip/.git" ] ; then
+      cd /usr/pkgsrc
+      git fetch --all
+      git checkout master
+      git pull
+   else
+      echo >&2 "ERROR: /usr/pkgsrc/wip is not initialised as a Git repository!"
       exit 1
    fi
 
