Further improvements and clean-ups.

diff --git a/scripts/30-development b/scripts/30-development
--- a/scripts/30-development
+++ b/scripts/30-development
@@ -19,7 +19,7 @@
 # Contact: dreibh@simula.no
 
 # Bash options:
-set -ex
+set -exu
 
 
 # ###########################################################################
@@ -55,10 +55,18 @@ set -ex
 # ###########################################################################
 
 
+# ====== Check/set environment variables ====================================
+if [ ! -e /etc/os-release ] ; then
+   echo >&2 "ERROR: /etc/os-release does not exist!"
+   exit 1
+fi
+. /etc/os-release
+
+
 # ====== Package installation ===============================================
 
 # ------ Ubuntu/Debian ------------------------------------------------------
-if [ -e /usr/bin/apt-get ] ; then
+if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
 
    # Programs:
    packages="
@@ -133,8 +141,9 @@ if [ -e /usr/bin/apt-get ] ; then
    done
    find /etc/apt/sources.list.d -name "*.sources" -exec sed -e 's/^Types: deb[ \t]*$/Types: deb deb-src/g' -i {} \;
 
+
 # ------ Fedora -------------------------------------------------------------
-elif [ -e /usr/bin/dnf ] ; then
+elif [ "${ID}" == "fedora" ] ; then
 
    # Programs:
    packages="
@@ -195,7 +204,7 @@ elif [ -e /usr/bin/dnf ] ; then
 
 
 # ------ FreeBSD ------------------------------------------------------------
-elif [ -e /usr/sbin/pkg ] ; then
+elif [ "${ID}" == "freebsd" ] ; then
 
    # Programs:
    packages="
@@ -252,6 +261,13 @@ elif [ -e /usr/sbin/pkg ] ; then
    git fetch --all
    git checkout main
    git pull
+
+
+# ------ Unknown ------------------------------------------------------------
+else
+
+   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
+   exit 1
 
 fi
 
diff --git a/scripts/31-allow-wireshark-as-user b/scripts/31-allow-wireshark-as-user
--- a/scripts/31-allow-wireshark-as-user
+++ b/scripts/31-allow-wireshark-as-user
@@ -19,36 +19,47 @@
 # Contact: dreibh@simula.no
 
 # Bash options:
-set -ex
+set -exu
 
 
 # ====== Check environment variables ========================================
-if [ "${USER_NAME}" == "" ] ; then
+if [ ! -v USER_NAME ] ; then
    echo >&2 "Usage: env USER_NAME=<user> $0"
    echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
    exit 1
 fi
+if [ ! -e /etc/os-release ] ; then
+   echo >&2 "ERROR: /etc/os-release does not exist!"
+   exit 1
+fi
+. /etc/os-release
 
 
 # ====== Allow Wireshark/T-Shark as regular user ============================
 
 # ------ Ubuntu/Debian ------------------------------------------------------
-if [ -e /usr/bin/apt-get ] ; then
+if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
 
    echo "wireshark-common wireshark-common/install-setuid boolean true" | sudo debconf-set-selections
    dpkg-reconfigure wireshark-common -fnoninteractive
 
 # ------ Fedora -------------------------------------------------------------
-elif [ -e /usr/bin/dnf ] ; then
+elif [ "${ID}" == "fedora" ] ; then
 
    # Allow Wireshark/T-Shark as regular user:
    usermod -a -G wireshark "${USER_NAME}"
 
 # ------ FreeBSD ------------------------------------------------------------
-elif [ -e /usr/sbin/pkg ] ; then
+elif [ "${ID}" == "freebsd" ] ; then
 
    # Allow Wireshark/T-Shark as regular user:
    # The user is already in group "wheel". Allow it to read from /dev/bpf:
    chmod g+r /dev/bpf
+
+# ------ Unknown ------------------------------------------------------------
+else
+
+   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
+   exit 1
 
 fi
diff --git a/scripts/51-nornet-development b/scripts/51-nornet-development
--- a/scripts/51-nornet-development
+++ b/scripts/51-nornet-development
@@ -19,13 +19,21 @@
 # Contact: dreibh@simula.no
 
 # Bash options:
-set -ex
+set -exu
+
+
+# ====== Check/set environment variables ====================================
+if [ ! -e /etc/os-release ] ; then
+   echo >&2 "ERROR: /etc/os-release does not exist!"
+   exit 1
+fi
+. /etc/os-release
 
 
 # ====== Package installation ===============================================
 
 # ------ Ubuntu/Debian ------------------------------------------------------
-if [ -e /usr/bin/apt-get ] ; then
+if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
 
    packages="
       nornet-development
@@ -34,9 +42,8 @@ if [ -e /usr/bin/apt-get ] ; then
    # shellcheck disable=SC2086
    env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y --no-install-recommends ${packages}
 
-
 # ------ Fedora -------------------------------------------------------------
-elif [ -e /usr/bin/dnf ] ; then
+elif [ "${ID}" == "fedora" ] ; then
 
    packages="
       nornet-development
@@ -45,11 +52,16 @@ elif [ -e /usr/bin/dnf ] ; then
    # shellcheck disable=SC2086
    /usr/bin/dnf install -y ${packages}
 
-
 # ------ FreeBSD ------------------------------------------------------------
-elif [ -e /usr/sbin/pkg ] ; then
+elif [ "${ID}" == "freebsd" ] ; then
 
    # TBD!
    true
+
+# ------ Unknown ------------------------------------------------------------
+else
+
+   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
+   exit 1
 
 fi
diff --git a/scripts/86-dbeaver b/scripts/86-dbeaver
--- a/scripts/86-dbeaver
+++ b/scripts/86-dbeaver
@@ -19,7 +19,7 @@
 # Contact: dreibh@simula.no
 
 # Bash options:
-set -ex
+set -exu
 
 
 # ====== Check environment variables ========================================
@@ -36,20 +36,36 @@ fi
 
 
 # ====== Install DBeaver Community Edition ==================================
+
+# ------ Debian -------------------------------------------------------------
 if [ "${ID}" == "debian" ] ; then
+
    env DEBIAN_FRONTEND=noninteractive apt install -y  --no-install-recommends flatpak
    flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
    flatpak install -y flathub io.dbeaver.DBeaverCommunity
+
+# ------ Ubuntu -------------------------------------------------------------
 elif [ "${ID}" == "ubuntu" ] ; then
+
    rm -f /etc/apt/preferences.d/block-snapd.pref
    env DEBIAN_FRONTEND=noninteractive apt install -y  --no-install-recommends snapd
    snap install dbeaver-ce
+
+# ------ Fedora -------------------------------------------------------------
 elif [ "${ID}" == "fedora" ] ; then
+
    wget -O /tmp/dbeaver.rpm "https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm"
    sudo dnf install -y /tmp/dbeaver.rpm
+
+# ------ FreeBSD ------------------------------------------------------------
 elif [ "${ID}" == "freebsd" ] ; then
+
    true   # FIXME!
+
+# ------ Unknown ------------------------------------------------------------
 else
-   echo >&2 "ERROR: No DBeaver CE installation recipe for ID=${ID}!"
+
+   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
    exit 1
+
 fi
diff --git a/scripts/88-rserpooldemo b/scripts/88-rserpooldemo
--- a/scripts/88-rserpooldemo
+++ b/scripts/88-rserpooldemo
@@ -19,7 +19,7 @@
 # Contact: dreibh@simula.no
 
 # Bash options:
-set -ex
+set -exu
 
 
 # ====== Check environment variables ========================================
@@ -145,9 +145,12 @@ elif [ "${ID}" == "freebsd" ] ; then
       sudo ln -s /usr/local/share/rserpooldemo /usr/share/rserpooldemo
    fi
 
+# ------ Unknown ------------------------------------------------------------
 else
-   echo >&2 "ERROR: No RSerPoolDemo installation recipe for ID=${ID}!"
+
+   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
    exit 1
+
 fi
 
 
