Another update.

diff --git a/scripts/31-install-docker b/scripts/31-install-docker
--- a/scripts/31-install-docker
+++ b/scripts/31-install-docker
@@ -22,6 +22,14 @@
 set -exu
 
 
+# ====== Check/set environment variables ====================================
+if [ ! -e /etc/os-release ] ; then
+   echo >&2 "ERROR: /etc/os-release does not exist!"
+   exit 1
+fi
+. /etc/os-release
+
+
 # ====== Package installation ===============================================
 
 # ------ Ubuntu/Debian ------------------------------------------------------
