Improved scripts.

diff --git a/scripts/89-hipercontracer b/scripts/89-hipercontracer
--- a/scripts/89-hipercontracer
+++ b/scripts/89-hipercontracer
@@ -28,6 +28,11 @@ if [ "${USER_NAME}" == "" ] ; then
    echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
    exit 1
 fi
+if [ ! -e /etc/os-release ] ; then
+   echo >&2 "ERROR: /etc/os-release is not available!"
+   exit 1
+fi
+. /etc/os-release
 
 
 # ====== Prepare source repositories ========================================
@@ -48,35 +53,14 @@ fi
 # ====== Build ==============================================================
 cd "/home/${USER_NAME}/src/hipercontracer"
 
-# Build the upcoming version 2.0
+# NOTE: Build the upcoming version 2.0
 sudo -u "${USER_NAME}" git checkout dreibh/udpping
 
-# ------ Install DBeaver CE and prepare build -------------------------------
-cores=1
-if [ -e /etc/os-release ] ; then
-   . /etc/os-release
-   if [ "${ID}" == "debian" ] ; then
-      ci/get-dependencies debian --install
-      cores="$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo "1")"
-      env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y  --no-install-recommends flatpak
-      sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
-      flatpak install -y flathub io.dbeaver.DBeaverCommunity
-   elif [ "${ID}" == "ubuntu" ] ; then
-      ci/get-dependencies ubuntu --install
-      cores="$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo "1")"
-      rm -f /etc/apt/preferences.d/block-snapd.pref
-      env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y  --no-install-recommends snapd
-      snap install dbeaver-ce
-   elif [ "${ID}" == "fedora" ] ; then
-      ci/get-dependencies ubuntu --install
-      cores="$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo "1")"
-   elif [ "${ID}" == "freebsd" ] ; then
-      ci/get-dependencies freebsd --install
-      cores="$(sysctl -a | grep 'hw.ncpu' | cut -d ':' -f2 | tr -d ' ' || echo "1")"
-   fi
-fi
-
 # ------ Build and install --------------------------------------------------
+cores=$(getconf _NPROCESSORS_ONLN 2>/dev/null || \
+           sysctl -a | grep 'hw.ncpu' | cut -d ':' -f2 | tr -d ' ' || \
+              echo "1")
+sudo -u "${USER_NAME}" ci/get-dependencies "${ID}" --install
 sudo -u "${USER_NAME}" cmake . -DCMAKE_INSTALL_PREFIX=/usr
 sudo -u "${USER_NAME}" make -j"${cores}"
 make install
