Added Solaris work-around for VirtualBox mouse service issue (https://www.illumos.org/issues/18284).

diff --git a/scripts/90-install-guest-utils b/scripts/90-install-guest-utils
--- a/scripts/90-install-guest-utils
+++ b/scripts/90-install-guest-utils
@@ -312,6 +312,11 @@ elif [ "${ID}" == "sunos" ] ; then
    if ! prtconf -vp | grep -qE "pci80ee" ; then
       pkg install virtualbox-additions || [ $? -eq 4 ]
 
+      # FIXME: Work-around for  mouse service failing under VirtualBox!
+      # Bug report: https://www.illumos.org/issues/18284
+      svcadm disable svc:/application/virtualbox/vboxmslnk:default || true
+      svcadm clear svc:/application/virtualbox/vboxmslnk:default || true
+
    # ------ QEMU ------------------------------------------------------------
    elif ! prtdiag | grep -qE "pci1af4,3|isa|asy" ; then
       # See https://gist.github.com/jimklimov/b79ef519add34af96e1fcc59de58165c
