Improved script.

diff --git a/scripts/99-clean-up b/scripts/99-clean-up
--- a/scripts/99-clean-up
+++ b/scripts/99-clean-up
@@ -23,6 +23,11 @@ set -exu
 
 
 # ====== Check/set environment variables ====================================
+if [ ! -e /etc/os-release ] ; then
+   echo >&2 "ERROR: /etc/os-release does not exist!"
+   exit 1
+fi
+. /etc/os-release
 UNAME="$(uname)"
 
 
@@ -40,24 +45,41 @@ fi
 
 
 # ====== Clean up packages  =================================================
-if [ "${UNAME}" == "Linux" ] ; then
-   # ------ Ubuntu ----------------------------------------------------------
-   if [ -x /usr/bin/apt-get ] ; then
-      /usr/bin/apt-get update
-      env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get dist-upgrade -y
-      env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get autoremove -y --purge
-      if [ -x /usr/bin/apt-file ] ; then
-         /usr/bin/apt-file update
-      fi
-      if [ -x /usr/bin/apt-show-versions ] ; then
-         /usr/bin/apt-show-versions -i
-      fi
-      /usr/bin/apt-get clean
 
-   # ------ Fedora ----------------------------------------------------------
-   elif [ -x /usr/bin/dnf ] ; then
-      /usr/bin/dnf clean all
+# ------ Ubuntu -------------------------------------------------------------
+if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
+
+   /usr/bin/apt-get update
+   env DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=l /usr/bin/apt-get dist-upgrade -y
+   if [ "${ID}" == "ubuntu" ] ; then
+      dhcpcd || true   # FIXME: Work-around for stopped networking in Ubuntu 24.04
    fi
+   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get autoremove -y --purge
+   if [ -x /usr/bin/apt-file ] ; then
+      /usr/bin/apt-file update
+   fi
+   if [ -x /usr/bin/apt-show-versions ] ; then
+      /usr/bin/apt-show-versions -i
+   fi
+   /usr/bin/apt-get clean
+
+# ------ Fedora -------------------------------------------------------------
+elif [ "${ID}" == "fedora" ] ; then
+
+   /usr/bin/dnf clean all
+
+# ------ FreeBSD ------------------------------------------------------------
+elif [ "${ID}" == "freebsd" ] ; then
+
+   /usr/sbin/pkg upgrade -y
+   /usr/sbin/pkg clean -y
+
+# ------ Unknown ------------------------------------------------------------
+else
+
+   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
+   exit 1
+
 fi
 
 
