Configuration improvements.

diff --git a/scripts/clean-up b/scripts/clean-up
--- a/scripts/clean-up
+++ b/scripts/clean-up
@@ -25,10 +25,14 @@ set -ex
 UNAME="$(uname)"
 
 
+# ====== Clean up temporary files ===========================================
+sudo -u "${USER_NAME}" rm -rf /home/"${USER_NAME}"/tmp/* >/dev/null 2>&1 || true
+
+
 # ====== Clean up packages  =================================================
 
 if [ "${UNAME}" == "Linux" ] ; then
-   # ------ Ubuntu -------------------------------------------------------------
+   # ------ Ubuntu ----------------------------------------------------------
    if [ -x /usr/bin/apt-get ] ; then
       /usr/bin/apt-get update
       if [ -x /usr/bin/apt-file ] ; then
@@ -38,7 +42,7 @@ if [ "${UNAME}" == "Linux" ] ; then
       env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get autoremove -y --purge
       /usr/bin/apt-get clean
 
-   # ------ Fedora -------------------------------------------------------------
+   # ------ Fedora ----------------------------------------------------------
    elif [ -x /usr/bin/dnf ] ; then
       /usr/bin/dnf clean all
    fi
