Improved script.

diff --git a/scripts/prepare-development-environment b/scripts/prepare-development-environment
--- a/scripts/prepare-development-environment
+++ b/scripts/prepare-development-environment
@@ -22,14 +22,42 @@
 set -ex
 
 
-# ###### NorNet development configuration ###################################
+# ###### Development configuration ##########################################
 
 # ------ Ubuntu -------------------------------------------------------------
-if [ -e /usr/bin/apt-get ] ; then
-   /usr/bin/apt-get update
-   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y nornet-development
+if [ -e /etc/apt/sources.list ] ; then
+   for list in /etc/apt/sources.list `find /etc/apt/sources.list.d -name "*.list"`; do
+      cat ${list} | grep "^deb \(.*\)$" | sed -e "s/deb[ \t]*//g" | xargs -n1 -i§ echo "s@^#[ \t]*deb-src \(§\)[ \t]*\$@deb-src \\1@g" >${list}.sed
+      cat ${list} | sed -f ${list}.sed >${list}.new
+      diff ${list} ${list}.new || true
+      mv ${list}.new ${list}
+      rm -f ${list}.sed
+   done
 
-# ------ Fedora -------------------------------------------------------------
-elif [ -e /usr/bin/dnf ] ; then
-   /usr/bin/dnf install -y nornet-development
+   # Add commented-out debugging symbols repository:
+   (
+      echo ""
+      echo "# Ubuntu debugging symbols repositories:"
+      echo "# To install the key: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F2EDC64DC5AEE1F6B9C621F0C8CAB6595FDFF622"
+      echo "# deb http://ddebs.ubuntu.com ${codename} main restricted universe multiverse"
+      echo "# deb http://ddebs.ubuntu.com ${codename}-updates main restricted universe multiverse"
+      echo "# deb http://ddebs.ubuntu.com ${codename}-proposed main restricted universe multiverse"
+   ) >>/etc/apt/sources.list
+   apt install ubuntu-dbgsym-keyring || apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F2EDC64DC5AEE1F6B9C621F0C8CAB6595FDFF622
+
+   # Add commented-out MPTCP repository:
+   codename=`lsb_release -c -s`
+   (
+      echo ""
+      echo "# Thomas Dreibholz's MPTCP kernel repository:"
+      echo "# To install the key: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 21412672518D8B2D1862EFEF5CD5D12AA0877B49"
+      echo "# deb [arch=amd64] https://packages.nntb.no/nornet-kernel/ubuntu/ ${codename} ${codename}-kernel"
+      echo "# deb-src [arch=amd64] https://packages.nntb.no/nornet-kernel/ubuntu/ ${codename} ${codename}-kernel"
+   ) >>/etc/apt/sources.list
+   apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 21412672518D8B2D1862EFEF5CD5D12AA0877B49
+
+   # Clean up old installer files:
+   rm -f /etc/apt/sources.list.curtin.old /etc/apt/sources.list.save
+
+   /usr/bin/apt-get update
 fi
