Using POSIX Shell for initial Docker container preparation.

diff --git a/scripts/prepare-docker-container b/scripts/prepare-docker-container
--- a/scripts/prepare-docker-container
+++ b/scripts/prepare-docker-container
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/sh
 # ==========================================================================
 #  ___         _        _ _      _   _            ___         _      _
 # |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
@@ -28,8 +28,8 @@
 #
 # Contact: thomas.dreibholz@gmail.com
 
-# Bash options:
-set -euxo pipefail
+# POSIX Shell options:
+set -eu
 
 
 # ###### Print script name, to make Packer output easier readable ###########
@@ -39,7 +39,7 @@ if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
    figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;32m█\e[22m" "\e[1;32m█\e[0m"
    LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;32m█" "▄" "█\e[0m"
 else
-   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
+   printf "\x1b[1;34;22m########## %s ##########\033[0m\n" "$(basename "$0")"
 fi
 
 # Enable printing the command-lines executed:
@@ -49,58 +49,48 @@ set -x
 # ###### Main program #######################################################
 
 # ====== Check/set environment variables ====================================
-if [ ! -v USER_NAME ]     || [ "${USER_NAME}"     == "" ] || \
-   [ ! -v USER_REALNAME ] || [ "${USER_REALNAME}" == "" ] || \
-   [ ! -v USER_PASSWORD ] || [ "${USER_PASSWORD}" == "" ] ; then
-   echo >&2 "Usage: env USER_NAME=<user> USER_REALNAME=\"<full user name>\" PASSWORD=\"<password>\" $0"
-   echo >&2 "Example: sudo env USER_NAME=nornetpp USER_REALNAME=\"NorNet Praesum Presum\" \" PASSWORD=\"test\" $0"
+if [ -z "${USER_NAME:-}" ] || [ -z "${USER_REALNAME:-}" ] || [ -z "${USER_PASSWORD:-}" ] ; then
+   echo "Usage: env USER_NAME=<user> USER_REALNAME=\"<full user name>\" USER_PASSWORD=\"<password>\" $0" >&2
+   echo "Example: sudo env USER_NAME=nornetpp USER_REALNAME=\"NorNet Praesum Presum\" USER_PASSWORD=\"test\" $0" >&2
    exit 1
 fi
 
 # ====== Obtain system details ==============================================
 UNAME="$(uname)"
 NAME="${UNAME}"
-ID="${UNAME,,}"
+ID=$(echo "$UNAME" | tr '[:upper:]' '[:lower:]')
 VERSION="$(uname -r)"
-VERSION_ID="${VERSION/_*/}"
+VERSION_ID="${VERSION%%_*}"
 if [ -f /etc/os-release ] ; then
    . /etc/os-release
 fi
 
-
 # ====== Make sure that "sudo" is available =================================
 
 # ------ Ubuntu/Debian ------------------------------------------------------
-if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
-   # apt-show-versions does not work with compressed indices:
-   # https://askubuntu.com/questions/916199/install-apt-show-versions-inside-an-ubuntu-docker-container
-   rm -f /etc/apt/apt.conf.d/docker-gzip-indexes
+case "${ID}" in
+   ubuntu|debian)
+      # apt-show-versions does not work with compressed indices:
+      # https://askubuntu.com/questions/916199/install-apt-show-versions-inside-an-ubuntu-docker-container
+      rm -f /etc/apt/apt.conf.d/docker-gzip-indexes
 
-   apt-get update -qq
-   env DEBIAN_FRONTEND=noninteractive apt-get install -y sudo
-
-# ------ Fedora -------------------------------------------------------------
-elif [ "${ID}" == "fedora" ] ; then
-   dnf install --setopt=install_weak_deps=False -y sudo
-
-# ------ OpenSUSE -----------------------------------------------------------
-elif [[ "${ID}" =~ ^opensuse- ]] ; then
-
-   zypper --non-interactive install --no-recommends -y bash sudo
-
-# ------ Alpine -------------------------------------------------------------
-elif [ "${ID}" == "alpine" ] ; then
-
-   apk add bash doas shadow sudo
-
-# ------ Unknown ------------------------------------------------------------
-else
-
-   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
-   exit 1
-
-fi
-
+      apt-get update -qq
+      env DEBIAN_FRONTEND=noninteractive apt-get install -y sudo
+      ;;
+   fedora)
+      dnf install --setopt=install_weak_deps=False -y sudo
+      ;;
+   opensuse-*)
+      zypper --non-interactive install --no-recommends -y bash sudo system-group-wheel
+      ;;
+   alpine)
+      apk add bash doas shadow sudo
+      ;;
+   *)
+      echo "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!" >&2
+      exit 1
+      ;;
+esac
 
 # ====== Create user ========================================================
 mkdir -p "/home/${USER_NAME}"
@@ -113,30 +103,32 @@ useradd -s /bin/bash \
    "${USER_NAME}"
 echo "${USER_NAME}:${USER_PASSWORD}" | chpasswd
 chown "${USER_NAME}:${USER_NAME}" "/home/${USER_NAME}"
-if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
-   # Debian/Ubuntu: group is "sudo"
-   usermod -aG sudo "${USER_NAME}"
-elif [ "${ID}" == "fedora" ] ; then
-   # Fedora: group is "wheel"
-   usermod -aG wheel "${USER_NAME}"
-elif [[ "${ID}" =~ ^opensuse- ]] ; then
-   usermod -aG wheel "${USER_NAME}"
-elif [ "${ID}" == "alpine" ] ; then
-   echo 'permit nopass :wheel' >/etc/doas.d/wheel.conf
-   addgroup sudo
-   usermod -a -G sudo "${USER_NAME}"
-   sed -e 's/^# %sudo /%sudo /' -i /etc/sudoers
-   usermod -aG wheel "${USER_NAME}"
-fi
+
+case "${ID}" in
+   ubuntu|debian)
+      # Debian/Ubuntu: group is "sudo"
+      usermod -aG sudo "${USER_NAME}"
+      ;;
+   fedora|opensuse-*)
+      # Fedora/OpenSUSE: group is "wheel"
+      usermod -aG wheel "${USER_NAME}"
+      ;;
+   alpine)
+      echo 'permit nopass :wheel' >/etc/doas.d/wheel.conf
+      addgroup sudo
+      usermod -a -G sudo "${USER_NAME}"
+      sed -e 's/^# %sudo /%sudo /' -i /etc/sudoers
+      usermod -aG wheel "${USER_NAME}"
+      ;;
+esac
 
 
 # ====== Make sure that "systemctl" is available ============================
-
-# ------ Ubuntu/Debian ------------------------------------------------------
-if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
-   env DEBIAN_FRONTEND=noninteractive apt-get install -y systemctl || true
-
-# ------ Fedora -------------------------------------------------------------
-elif [ "${ID}" == "fedora" ] ; then
-   dnf install --setopt=install_weak_deps=False -y systemd
-fi
+case "${ID}" in
+   ubuntu|debian)
+      env DEBIAN_FRONTEND=noninteractive apt-get install -y systemctl || true
+      ;;
+   fedora)
+      dnf install --setopt=install_weak_deps=False -y systemd
+      ;;
+esac
