Improved script.

diff --git a/scripts/prepare-docker-container b/scripts/prepare-docker-container
--- a/scripts/prepare-docker-container
+++ b/scripts/prepare-docker-container
@@ -57,11 +57,15 @@ if [ ! -v USER_NAME ]     || [ "${USER_NAME}"     == "" ] || \
    exit 1
 fi
 
-if [ ! -e /etc/os-release ] ; then
-   echo >&2 "ERROR: /etc/os-release does not exist!"
-   exit 1
+# ====== Obtain system details ==============================================
+UNAME="$(uname)"
+NAME="${UNAME}"
+ID="${UNAME,,}"
+VERSION="$(uname -r)"
+VERSION_ID="${VERSION/_*/}"
+if [ -f /etc/os-release ] ; then
+   . /etc/os-release
 fi
-. /etc/os-release
 
 
 # ====== Make sure that "sudo" is available =================================
@@ -78,11 +82,28 @@ if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
 # ------ Fedora -------------------------------------------------------------
 elif [ "${ID}" == "fedora" ] ; then
    dnf install --setopt=install_weak_deps=False -y sudo
+
+# ------ OpenSUSE -----------------------------------------------------------
+elif [[ "${ID}" =~ ^opensuse- ]] ; then
+
+   zypper --non-interactive install --no-recommends -y bash sudo
+
+# ------ Alpine -------------------------------------------------------------
+elif [ "${ID}" == "alpine" ] ; then
+
+   apk add bash doas shadow sudo
+
+# ------ Unknown ------------------------------------------------------------
+else
+
+   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
+   exit 1
+
 fi
 
 
 # ====== Create user ========================================================
-mkdir -p /home/"${USER_NAME}"
+mkdir -p "/home/${USER_NAME}"
 groupadd "${USER_NAME}"
 useradd -s /bin/bash \
    -c "${USER_REALNAME}" \
@@ -91,12 +112,20 @@ useradd -s /bin/bash \
    -p "${USER_PASSWORD}" \
    "${USER_NAME}"
 echo "${USER_NAME}:${USER_PASSWORD}" | chpasswd
-chown "${USER_NAME}":"${USER_NAME}" /home/"${USER_NAME}"
+chown "${USER_NAME}:${USER_NAME}" "/home/${USER_NAME}"
 if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
    # Debian/Ubuntu: group is "sudo"
    usermod -aG sudo "${USER_NAME}"
-else
+elif [ "${ID}" == "fedora" ] ; then
    # Fedora: group is "wheel"
+   usermod -aG wheel "${USER_NAME}"
+elif [[ "${ID}" =~ ^opensuse- ]] ; then
+   usermod -aG wheel "${USER_NAME}"
+elif [ "${ID}" == "alpine" ] ; then
+   echo 'permit nopass :wheel' >/etc/doas.d/wheel.conf
+   addgroup sudo
+   usermod -a -G sudo "${USER_NAME}"
+   sed -e 's/^# %sudo /%sudo /' -i /etc/sudoers
    usermod -aG wheel "${USER_NAME}"
 fi
 
