Improved scripts.

diff --git a/http/freebsd-3disks/installerconfig b/http/freebsd-3disks/installerconfig
--- a/http/freebsd-3disks/installerconfig
+++ b/http/freebsd-3disks/installerconfig
@@ -23,12 +23,25 @@ DISTRIBUTIONS="kernel.txz base.txz"
 # that bsdinstall runs /usr/libexec/bsdinstall/zfsboot.
 ZFSBOOT_DISKS="manual"
 
+. /etc/os-release
+_UNAME_R="$(uname -r)"
+_UNAME_R="${_UNAME_R%-p*}"
+export BSDINSTALL_DISTSITE="http://download.freebsd.org/ftp/releases/$(uname -m)/$(uname -p)/${_UNAME_R}"
+
 export nonInteractive="YES"
+
+
+# NOTE:
+# For unknown reason FreeBSD 15.0's bsdinstall removes the existing
+# resolv.conf, and dhclient fails to add it again. Make sure that
+# at least some public DNS servers are there for installation:
+echo 'nameserver 1.1.1.1' >>/tmp/bsdinstall_etc/resolv.conf
+echo 'nameserver 9.9.9.9' >>/tmp/bsdinstall_etc/resolv.conf
 
 
 #!/bin/sh
 
-set -ex
+set -eux
 
 # ====== Basic configuration ================================================
 
@@ -41,7 +54,7 @@ sysrc ifconfig_$interface="dhcp"
 sysrc ifconfig_"$interface"_ipv6="inet6 accept_rtadv"
 sysrc ipv6_activate_all_interfaces="YES"
 sysrc ipv6_privacy="YES"
-dhclient $interface
+# dhclient $interface
 
 # Enable basic daemons:
 sysrc dumpdev="AUTO"
